### ISSUE TITLE
I cannot get your mod to work do you have a basic template?

### ISSUE THREAD

**Issue by DPxKnightxZero** [superzanti/ServerSync#1]
Its an amazing mod but I am not very code savvy how the hell do I make your mod do anything? Currently I have these settings and it doesn't show or do anything!

ServerSync 1.7.10
# Configuration file

gui {
    # The ID of the button that connects to the server and updates [range: 0 ~ 2147483647, default: 6001]
    I:ButtonID=2147483647
}

ignoredfiles {
    # These files are ignored by serversync [default: [./mods/CustomMainMenu-MC1.7.10-1.5.jar], [./config/CustomMainMenu/mainmenu.json], [./config/serversync.cfg], [./config/forge.cfg], [./config/forgeChunkLoading.cfg], [./config/splash.properties], [./mods/serversync-2.0.jar]]
    S:IGNORE_LIST <
        ./mods/CustomMainMenu-MC1.7.10-1.5.jar
        ./config/CustomMainMenu/mainmenu.json
        ./config/serversync.cfg
        ./config/forge.cfg
        ./config/forgeChunkLoading.cfg
        ./config/splash.properties
        ./mods/serversync-2.0.jar
     >
}

serverconnection {
    # The port in which the minecraft server is running, not the serversync port [range: 1 ~ 49151, default: 25565]
    I:MINECRAFT_PORT=26164

    # The IP address of the server [default: 127.0.0.1]
    S:SERVER_IP=192.99.98.222

    # The port that your server will be serving on [range: 1 ~ 49151, default: 38067]
    I:SERVER_PORT=38067
}

serverencryption {
    # The checksum command security key phrase [default: 226190d94b21d1b0c7b1a42d855e419d]
    S:SECURE_CHECKSUM=226190d94b21d1b0c7b1a42d855e419d

    # The exists command security key phrase [default: e087923eb5dd1310f5f25ddd5ae5b580]
    S:SECURE_EXISTS=e087923eb5dd1310f5f25ddd5ae5b580

    # The exit command security key phrase [default: f24f62eeb789199b9b2e467df3b1876b]
    S:SECURE_EXIT=f24f62eeb789199b9b2e467df3b1876b

    # The recursive command security key phrase [default: f8e45531a3ea3d5c1247b004985175a4]
    S:SECURE_RECURSIVE=f8e45531a3ea3d5c1247b004985175a4

    # The update command security key phrase [default: 3ac340832f29c11538fbe2d6f75e8bcc]
    S:SECURE_UPDATE=3ac340832f29c11538fbe2d6f75e8bcc
}

Custom Main Menu 1.7.10

{
    "images":
    {
        "title":
        {
            "image" : "custommainmenu:textures/gui/minecraft.png",
            "posX" : -137,
            "posY" : 30,
            "width" : 512,
            "height" : 512,
            "alignment" : "top_center"
        }
    },
    
    "buttons":
    {
    
        "Death Plague Gaming":
        {
            "text" : "Death Plague Gaming",
            "posX" : -100,
            "posY" : -24,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openLink",
                "link" : "http://deathplague.enjin.com/"
            }
        },
    
        "ModpackChangelog":
        {
            "text" : "Modpack Changelog",
            "posX" : -100,
            "posY" : 0,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },
    
        "ModpackUpdate":
        {
            "text" : "Modpack Update",
            "posX" : -100,
            "posY" : 24,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "wrappedButton",
                "wrappedButton" : "2147483647"
            }
        },
        
        "singleplayer":
        {
            "text" : "menu.singleplayer",
            "posX" : -100,
            "posY" : 48,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "singleplayer"
            }
        },
        
        "multiplayer":
        {
            "text" : "menu.multiplayer",
            "posX" : -100,
            "posY" : 72,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "multiplayer"
            }
        },
        
        "mods":
        {
            "text" : "Mods",
            "posX" : -100,
            "posY" : 96,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "mods"
            }
        },
            
        "options":
        {
            "text" : "menu.options",
            "posX" : -100,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "options"
            }
        },
        
        "quit":
        {
            "text" : "menu.quit",
            "posX" : 2,
            "posY" : 132,
            "width" : 98,
            "height" : 20,
            "action" : 
            {
                "type" : "quit"
            }
        },
        
        "language":
        {
            "text" : "",
            "posX" : -124,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "languages"
            }
        },
        
        "refresh":
        {
            "text" : "",
            "posX" : -154,
            "posY" : 132,
            "width" : 20,
            "height" : 20,
            "texture" : "custommainmenu:textures/gui/buttons.png",
            "action" : 
            {
                "type" : "refresh"
            }
        }
    },
    
    "texts":
    {
        "mojang":
        {
            "text" : "Copyright Mojang AB. Do not distribute!",
            "posX" : -197,
            "posY" : -10,
            "color" : -1,
            "alignment" : "bottom_right"
        },
        
        "fml":
        {
            "text" : "",
            "posX" : 2,
            "posY" : -50,
            "color" : -1,
            "alignment" : "bottom_left"
        }
    },
    
    "other":
    {
        "splash-text":
        {
            "posX" : 90,
            "posY" : 70,
            "color" : -256,
            "alignment" : "top_center",
            "file" : "texts/splashes.txt"
        },
        
        "panorama":
        {
            "images" : "minecraft:textures/gui/title/background/panorama_%c.png",
            "animate" : true,
            "animationSpeed" : 1,
            "blur" : true,
            "gradient" : true
        }
    }
}

**Comment by lumien231** [comment]
Just fyi. you shouldn't really require cmm for this, you can use GuiScreenEvent.InitGuiEvent to add your own button to the main menu.

**Comment by superzanti** [comment]
Lumien231, I'm aware that It doesn't have to require CMM. I'm going to fix that in the future, but for now I wanted it because I didn't want to make my own menu. Again, I'll do it in the future.

DPxKnightxZero, First of all your button ID is wrong. What you're doing is binding my mod to one of the buttons on your homescreen. I should have made this a little easier to find out what the buttonid is, so I'll add support for finding the buttonid a little easier in the future.  What you want is probably something in the 6000's. Make sure both your server and your clients have the same config file for serversync.cfg.   Looking at your CMM config I don't see any button that would utilize my mod. My first suggestion would just to be to use the defaults for everything and just change the SERVER_IP field and the MINECRAFT_PORT field. then try clicking 'connect to the verse' and see if it works. Lets work through this and get it working! I'm very happy to know you're using my mod.

**Comment by DPxKnightxZero** [comment]
So I should use 6001 and just stay with default?

**Comment by superzanti** [comment]
When it stays at 'closing connections' That's most likely because it can't communicate with the server. Are you sure it's running on the server? Are you sure you have the ports right and the IP right? Did you port forward both the minecraft port and the serversync port?

Yeah, I'd say stay with the default. However if you look up how to use CMM youcan change the config file to your liking. e.g. You might not want it to say 'connect to the verse' but something else.

**Comment by DPxKnightxZero** [comment]
Okay so this is a template not a test Query Correct?

**Comment by superzanti** [comment]
Correct. But if you add buttons to it you'll have to change the buttonid. i.e. if you add the multiplayer button back in right before i've defined 'connect to the verse' button, you should change your buttonid to 6002.

Does it work when all the ports are forwarded and set up correctly?

**Comment by DPxKnightxZero** [comment]
Alright I need to make sure you know how I have it setup first off this is my server host information

IP	192.99.98.222	
Port	26164

This is how I have this segment of server sync configured.

gui {
    # The ID of the button that connects to the server and updates [range: 0 ~ 2147483647, default: 6001]
    I:ButtonID=6001 <- Don't Understand Formula 
}


serverconnection {
    # The port in which the minecraft server is running, not the serversync port [range: 1 ~ 49151, default: 25565]
    I:MINECRAFT_PORT=26164

    # The IP address of the server [default: 127.0.0.1]
    S:SERVER_IP=192.99.98.222

    # The port that your server will be serving on [range: 1 ~ 49151, default: 38067]
    I:SERVER_PORT=38067 <- Not sure what this does
}

**Comment by superzanti** [comment]
The SERVER_PORT is the port in which serversync sends files across. It needs to be forwarded as well as your MINECRAFT_PORT.  The ButtonID is simply the id the minecraft associates with a button. They're hard to find unless you know what you're doing. So for now just leave it at 6001 until you get the rest of the stuff working, then we can work on messing with the CMM config.

**Comment by DPxKnightxZero** [comment]
Okay thank you so I have to forward a port? How do I do that with a 24/7 host?

**Comment by DPxKnightxZero** [comment]
So how does a strangers client connect to the serversync server application do you mean to tell me they need to forward a port each time?

**Comment by DPxKnightxZero** [comment]
I am trying to streamline updates that make everything for my users a snap! Most don't know technology. They do understand technic.

**Comment by superzanti** [comment]
Forwarding a port is something you'll have to bring up with your provider.

The client doesn't need to do anything. The port only has to be forwarded for the server.

This sounds like exactly what you want, However, please have them read the disclaimer.

**Comment by DPxKnightxZero** [comment]
Okay thank you very much.
