### ISSUE TITLE
Config Problems

### ISSUE THREAD

**Issue by badboysuper** [superzanti/ServerSync#102]
#### Serversync Version: 
serversync-2.6.17
#### Minecraft Version: 
1.12.2
#### Issue: 
I am to stupid to use this
<details>
I am to stupid to use this. Well, I am not sure which port I have to configure in the Server config and I also dont know what port clients need to insert into there Sync window. I tried with the standard port (38067), but then it always said "Could not connect to server at...". And I tried the port of my server (25609) which made the server crash and respond: "Perhaps another server is already running on that port?". Can you maybe help me? What do I have to change in the server config and what does the client need to insert in the ServerSync window
<summary>Logs (serverysync & minecraft)</summary>
</details>

**Comment by badboysuper** [comment]
Ok thank you. So if the Server is hosted online from somewhere else, I can just take the minecraft server IP and give it to them: So in the IP section they insert the Server IP and in the lower Port section they leave the standard port?

**Comment by rheimus** [comment]
Yep that sounds right.
