### ISSUE TITLE
File duplication on Client Side

### ISSUE THREAD

**Issue by yotthani** [superzanti/ServerSync#103]
#### Serversync Version: 
serversync-2.6.17.jar
#### Minecraft Version: 
1.12.2
#### Issue: 
Server keeps both Files on client side if you move it on server side 
e.g. moved on File from /mods/ to /mods/1.12.2/ on server , on client side it keeps both versions if you have synced before moving

**Comment by rheimus** [comment]
Hmm, interesting edge case.

Indeed SS is not really doing any path comparison at the moment, nice find!

**Comment by yotthani** [comment]
Ok thx, i'm good in finding bugs in code but always not in mine , just in others ;)

**Comment by rheimus** [comment]
Closing as this issue has not turned up in a long time.
