### ISSUE TITLE
[Client] Update mode

### ISSUE THREAD

**Issue by Hexawolf** [superzanti/ServerSync#106]
There are some issued with mods synchronization. For example, apparently ServerSync does not delete older mods that are no longer in use by server, which might break client. What I'm suggesting is to add another "update mode" (a simple checkbox) which simply "wipes" all jar files that are not present on server. Of course some jars may be excluded by tweaking config.

**Comment by rheimus** [comment]
The goal of SS is to have the client mirror the servers mods.

If SS is not deleting mods that are not present on the server and are not user excluded in the configuration files then it is a bug.

**Comment by Hexawolf** [comment]
Oops!

tl;dr: this is invalid issue, was caused by miss-use of ServerSync due to #73 
By the way, I am fixing it right now, adding a slightly more intelligent Minecraft directory detection.
Closing this issue. Sorry...
