### ISSUE TITLE
Mod compatability issue

### ISSUE THREAD

**Issue by TheQuantumGeneral** [superzanti/ServerSync#11]
Having an issue which only arises by having Server Sync and Thermal foundation in the same instance.

http://pastebin.com/MaN4997N

Crashes to desktop on joining server, if I remove server sync or thermal foundation everything connects seamlessly. Not an issue for singleplayer.

**Comment by superzanti** [comment]
That is very strange. There may be some kind of compatibility issue. Can you give me the whole log? Not just the crash report?

**Comment by TheQuantumGeneral** [comment]
Here is the full log - https://paste.ee/p/4LBiF

**Comment by superzanti** [comment]
Are you using minecraft 1.7.10?

What version of forge are you using? A update to forge may fix all of this.

**Comment by superzanti** [comment]
Did this ever get resolved for you? Does this new version fix it?

https://github.com/superzanti/ServerSync/blob/master/build/libs/serversync-2.2.jar

**Comment by TheQuantumGeneral** [comment]
Using the latest build of Server Sync, tried on Forge 1403 and the new recommended and latest build 1448 I am still having the same crash, crash reports identical to the old. 

I tried removing the client side mods like Optifine, Cleanview, etc. It still appears to be something that happens when Thermal Foundation is added to the mix though. 

Tested with both Vanilla launcher and MultiMC, result is the same error posted above.

**Comment by superzanti** [comment]
I believe I also am using Thermal Foundation.

I would not be surprised if it was my mod. 

So far this is currently the hardest issue I have and I'm having trouble finding leads onto what it could be. I'm working to get it fixed as soon as I can for you.

**Comment by KingLemming** [comment]
I'm not entirely sure it's either mod directly. It may be an N-way interaction. ThermalFoundation doesn't really do anything during that part of the connection process, but a mod that has a dependency on TF might.

**Comment by KingLemming** [comment]
And just sort of a question...what happens if you try and replace a file when Java has an open file pointer to that resource?

We do maintain links to our config files, since they can be changed from within the game. The base concept may be sort of dangerous here.

**Comment by superzanti** [comment]
I do not replace the file until the java virtual machine has exited.

I run a deleteOnExit() and the client will have to update again to get the correct file after the current one has been deleted.

**Comment by DPxKnightxZero** [comment]
Do you have thaumcraft installed?

**Comment by superzanti** [comment]
No.

**Comment by TheQuantumGeneral** [comment]
Okay, after much fiddling the issue has been isolated and fixed and you will be glad to know it was neither TF or SS.

AOBD 1.6.2, deleted the mod and config file, re-downloaded it and ran it fresh, fixed the issue.

**Comment by superzanti** [comment]
I recently updated the mod, please download it off my github.

But the issue seems to be solved?

**Comment by TheQuantumGeneral** [comment]
Yep, using the latest build of your mod. Re-downloading AOBD seems to have fixed it though.

**Comment by superzanti** [comment]
So you no longer need to remove aobd ?

**Comment by TheQuantumGeneral** [comment]
No longer need to remove AOBD, the re-download of the same version fixed all issues. Thermal Foundation works fine in my instance now.

**Comment by superzanti** [comment]
Perfect. It's not the same version btw.    I should have named it 2.2.5 or something.
