### ISSUE TITLE
Enhancement Request: Remove files found on client that are "ignored" in config

### ISSUE THREAD

**Issue by syndicate25** [superzanti/ServerSync#111]
#### Issue: The mod ignores items listed in the config and does not download them, which is fine... but does not remove them if they are found on the client.  Items found on the client that are listed in the ignore section of the config file should be deleted, if found, from the client end.

**Comment by rheimus** [comment]
The ignore list is designed for clients to tell ServerSync to ignore files that they don't want to be deleted when trying to mirror the server.

e.g. You have Optifine installed and you don't want ServerSync to delete it as it is a client only mod.

Sounds like you would like a block list for clients, so you as a client can block servers from sending you particular mods / files?

This would be easy enough to make, though quite easily misused to break the purpose of SS.

**Comment by rheimus** [comment]
You may be able to achieve the desired result by adding the server only mods to the ignore list in the server config.

This tells the server to ignore the files in question essentially making ServerSync treat them like they don't exist.

**Comment by syndicate25** [comment]
On any version above 2.6.9, I've been unsuccessful in getting this to work.  I've started with fresh configs, and I've added the directory structure as you suggested.  The last version I tried was the latest release, and it still sent everything over, even though the server-only mods were clearly added to the ignore list on the server config.

I'll have to redo this when I get home and show you the config setup and the results.  I already downloaded the latest version again thinking I'd give it another go just in case I was messing something up.  Cross referencing your comment on the other issue I posted, I did in fact try adding something like this to the ignore list:

mods\filename.jar
or
mods/filename.jar

...and the files were still not ignored.  I'll give you more info when I have it.

**Comment by rheimus** [comment]
I can add a folder for server specific mods, it is a little funky though as I would need to copy said mods from servermods to mods at some point thereby duplicating files between the two directories.

Could potentially do something with symlinks though I don't know how/if forge handles that.

Seem like the real issue that you are facing is that serversync for whatever reason is not working properly in your environment, the two ignore lists (client/server) should let you achieve what you want.

**Comment by syndicate25** [comment]
If I just need to learn to properly set up the configs in the new version, then I will try that and let you know if it still doesn't work.  You're saying it's possible for a client with absolutely 0 configuration files, INCLUDING serversync, to not have server-only mods pushed to it on the initial sync?

**Comment by rheimus** [comment]
It should be yes.

If the server has the server only files in it's ignore list then it should not send them to clients when they try to sync regardless of what the client has configured.
