### ISSUE TITLE
muiltmc after serversync is complete minecraft wont start (crashing on .meta files?)

### ISSUE THREAD

**Issue by cmspeedau** [superzanti/ServerSync#112]
#### Serversync Version: 
2.6.17
#### Minecraft Version: 
1.12.2 forg1.12.2-14.23.4.2707
#### Issue: 
ImmersiveEngineering-core-0.12-81.jar.meta not recognized as a minecraft mod (not a problem)
not sure if this is stoping server sync from starting my mc client
<details>
<summary>Logs (serverysync & minecraft)</summary>
<pre>

Loading language file: en_au
No language file available for: en_au, defaulting to en_US
{UPDATE=d5d6805c7b5d138af3e4e77cb188b562eef213e2, UPDATE_NEEDED=66b09150bca17024dd2b73a5b0886eac5ee0f325, UPDATE_GET_SYNCABLE_DIRECTORIES=02cace6a1865b160c8225d920243a54fc820603d, UPDATE_GET_CLIENT_ONLY_FILES=6be8053804ac13c45125f128badbebf2a0d480df, FILE_GET_CONFIG=4ca30c302e7329e3d0f48eccfcda8bc9d394367e, FILE_GET_LIST=c4ea0ec9ebe4c75e8a7606dc9891c6fc1ffc23e0, FILE_COMPARE=5d141a046308b3d55daf0248c6fe2c20cd4c91f3, FILE_EXISTS=5935bab159ae1363e3be3b131a05cc9fa902f8ce, HANDSHAKE=431e970613f5fdf1c827a17353e96fd7d64816b9, INFO_LAST_UPDATE=f68f56e40ffe32c374d51241ff6852eca7070194, INFO_GET_FILESIZE=879529f09e32661836c2a065a72ff76f3f92ac0a, EXIT=a4181c315ad81f76e6b08bbdd8e0de517f2727c6}
File: ImmersiveEngineering-core-0.12-81.jar.meta not recognized as a minecraft mod (not a problem)
Sending update check to server
File: ImmersiveEngineering-core-0.12-81.jar.meta not recognized as a minecraft mod (not a problem)
File: ImmersiveEngineering-core-0.12-81.jar.meta not recognized as a minecraft mod (not a problem)
[com.superzanti.serversync.util.SyncFile@456234e4, com.superzanti.serversync.util.SyncFile@4c55b1b7, com.superzanti.serversync.util.SyncFile@25cf2d2a, com.superzanti.serversync.util.SyncFile@d4185f0, com.superzanti.serversync.util.SyncFile@59d045a8, com.superzanti.serversync.util.SyncFile@38698f2c, com.superzanti.serversync.util.SyncFile@64934376, com.superzanti.serversync.util.SyncFile@657c3411, com.superzanti.serversync.util.SyncFile@3edac013, com.superzanti.serversync.util.SyncFile@4a3e380b, com.superzanti.serversync.util.SyncFile@34c85ac9, com.superzanti.serversync.util.SyncFile@30902cfd, com.superzanti.serversync.util.SyncFile@58a2a8a4, com.superzanti.serversync.util.SyncFile@63672ddb, com.superzanti.serversync.util.SyncFile@158f3d6c, com.superzanti.serversync.util.SyncFile@24c90ce4]
Process exited with code 0.
</pre>
</details>
this feels like this is a simple fix problem? everytime it gets to File: ImmersiveEngineering-core-0.12-81.jar.meta it will not load up my client but server sync dose sync all the required mods over

**Comment by rheimus** [comment]
meta is a rather odd file extension, Is this a valid Minecraft mod?

ServerSync does not validate that files are working mods, it just looks inside the jar package for a modinfo file that lists various attributes of the mod (version / name etc).

The message reported is not considered a problem as some mods have non 'mod' files related to them, like flans packs.

**Comment by cmspeedau** [comment]
So why wouldn’t serversync start mc after anything I need to add

**Comment by rheimus** [comment]
That I am unsure, I have not personally tried to have MultiMC run SS before starting Minecraft.

Are you following the example that the user on Curse provided?

**Comment by rheimus** [comment]
Are you trying to use a particular modpack?

I can try to do some testing around it if so.

**Comment by cmspeedau** [comment]
All the mods 3 lite using muiltmc

**Comment by yotthani** [comment]
had the same problem  .. it somehow crashes on these meta files 
Workaround: for me was to put them  *.meta into ignore list

**Comment by cmspeedau** [comment]
I’ll try that when I’m at home

**Comment by cmspeedau** [comment]
i did the ignore *.meta tag but minecraft client still isnt loading after serversync has finished

**Comment by rheimus** [comment]
Closing this as file sync has had major changes since 3.x.x
