### ISSUE TITLE
Files listed in client ignore list are not being ignored

### ISSUE THREAD

**Issue by syndicate25** [superzanti/ServerSync#113]
#### Issue: Files listed in client ignore list are not being ignored and are synced anyway

[com.superzanti.serversync.util.Log:add:37]: LOG:Writing mods/AIImprovements-1.7.10-0.0.1b19-dev.jar to client Socket[addr=/removed,port=51851,localport=38067]...
20.06 23:29:20 [Server] ClientThread - /removed/INFO [STDOUT]: [com.superzanti.serversync.util.Log:add:37]: LOG:Finished writing file to client Socket[addr=/removed,port=51851,localport=38067]
20.06 23:29:21 [Server] ClientThread - /removed/INFO [STDOUT]: [com.superzanti.serversync.util.Log:add:37]: LOG:Recieved message from: /removed
20.06 23:29:21 [Server] ClientThread - /removed/INFO [STDOUT]: [com.superzanti.serversync.util.Log:add:37]: LOG:Writing filesize to client Socket[addr=/removed,port=51851,localport=38067]...
20.06 23:29:21 [Server] ClientThread - /removed/INFO [STDOUT]: [com.superzanti.serversync.util.Log:add:37]: LOG:Recieved message from: /removed
20.06 23:29:21 [Server] ClientThread - /removed/INFO [STDOUT]: [com.superzanti.serversync.util.Log:add:37]: LOG:Writing mods/underphangables-1.7.10-1.0.1.jar to client

That's just an example of 2 mods that are syncing that shouldn't be.  It's also deleting the serversync client config after every sync forcing me to recreate it every time.

<------> Starting deletion process <------>
<>fastcraft.ini deleted
<>serversync-client.cfg deleted
<>serversync-server.cfg deleted

/////

**EDIT:**

Here's what was deleted on my most recent sync:

https://pastebin.com/Cfqm9tDC

These are all crucial files and should not be deleted. I don't know what I'm doing wrong with the new versions. :/
/////

Here are my configs as they are set up after downloading 2.6.19:

Client config:
https://pastebin.com/0hke0VEf

Server config:
https://pastebin.com/zNf72mVd

I should note I didn't have ANY issues with serversync when I was using 2.6.9, but after trying any of the newer versions and trying to go BACK to 2.6.9, I can't seem to get things to work how I did before.  I have wiped configs between versions to make sure they are all set up properly but I can't seem to stop the server from sending the client all the "server only" files, and always wants to delete configs from the client end that it shouldn't be, regardless of how it's set up.

**Comment by rheimus** [comment]
The file ignore list root is the Minecraft folder.

All of your file ignore rules are currently looking for the files in Minecraft/*, to get the desired effect you would need to add the directory the mods are located in.

The resulting rule would look like: mods/myignoredmod.jar  or **/myignoredmod.jar if you want to ignore it from any folder.

The file ignore list is structured this way because we can include files to sync from any directory inside the minecraft folder so we need to be able to ignore from any folder as well.

**Comment by rheimus** [comment]
I should probably add some generated inline comments to the config files indicating how to use the lists.

**Comment by rheimus** [comment]
The wiki does have a section on the include / ignore lists here: https://github.com/superzanti/ServerSync/wiki/Ignore-&-Include-lists

**Comment by syndicate25** [comment]
Yes, I did find that.  I followed the documentation.  On any version above 2.6.9, I've been unsuccessful in getting this to work.  I've started with fresh configs, and I've added the directory structure as you suggested.  The last version I tried was the latest release, and it still sent everything over, even though the server-only mods were clearly added to the ignore list on the server config.  I should also say that on 2.6.9, I didn't have to specify the folder structure.  I used the directory list as the whitelist, and the other lists as the blacklist.

I'll have to redo this when I get home and show you the config setup and the results.  I already downloaded the latest version again thinking I'd give it another go just in case I was messing something up.  Cross referencing your comment on the other issue I posted, I did in fact try adding something like this to the ignore list:

mods\filename.jar
or
mods/filename.jar

...and the files were still not ignored.  I'll give you more info when I have it.

**Comment by rheimus** [comment]
Could you please give me an overview of the folder structure you have for Minecraft.

**Comment by syndicate25** [comment]
Sure.

Here's where everything is located:

C:\Users\<User>\AppData\Roaming\.minecraft 1.7.10\.minecraft

I'll attach a screenshot of the rest so you can see what's inside that folder.  Ignore the fact that it says I'm using version 2.6.19, because I just downloaded it and am going to try to reconfigure this again to try to get it to work.

![folder structure](https://user-images.githubusercontent.com/22588398/42071308-e17ed304-7b17-11e8-9ec7-295011f0de1d.png)
