### ISSUE TITLE
Allow to exclude directory in config. Feature Request

### ISSUE THREAD

**Issue by ZiroGX2** [superzanti/ServerSync#114]

**Comment by rheimus** [comment]
Looks like this works with glob patterns:
mods/nastyfolder/**
[Live Example](http://www.globtester.com/#p=eJzLzU8p1k%2FJT0%2FV19ICAB1QBAU%3D&r=eJy9ks0OwiAQhF%2BFcLdEbyrlXfgvCWUblhjt0wvh0pOatPG2h5lvZpLlJjyIjhJxpLMseqKC4yITwfKKdqQOUjlhWO2NnK%2FDZXneqZjBIDPgLXMALEYVkh8KctaMgqssOKtYwXexlcyNLdcN%2Bpu7Z3ftERXqsNqhrjyqw6%2FxbXjehO4A%2Fbc9lMnm9hcfIBqSCx4Zwmz7PWjnu%2FIN%2FQLfIQ%3D%3D&)
