### ISSUE TITLE
Twitch Integration

### ISSUE THREAD

**Issue by TakunSho** [superzanti/ServerSync#116]
#### Issue: Guide/Enhancement

Could we get a guide and the ability to launch a twitch launcher profile from the batch file? My friends and I primarily user Twitch (as horrible as it is sometimes). This has made updating packs super easy for me, but I want to make it easy on them too by getting it so that they either run the batch file to update then launch the twitch profile, or click the play button to have it launch directly before loading Minecraft. I'm not sure if this is possible though.

**Comment by rheimus** [comment]
Twitch does not appear to give you a way to hook startup events, nor does it appear to have any startup options to allow starting a specific profile.

Really the only option for full auto would be to manually start Minecraft passing it all of the required arguments for setting up the JVM & user authentication etc. This would require the batch to be run from within the users curse directory or to know where the users curse files are located.

How would you deliver said batch file to your users? (where would the batch file be run from)

**Comment by TakunSho** [comment]
I'm delivering the batch file through Twitch (I just included it in the modpack). As a result, it is stored in the modpack profile root directory Minecraft/Instances/<modpack>/Updater.bat. And I have them run the updater from there.

For reference, here is the batch file code:
```
SET pathToMinecraft=.
SET pathToLauncher=..\..\Install

java -jar %pathToMinecraft%\serversync-2.6.17.jar progress-only
```

**Comment by TakunSho** [comment]
Alright, I tried some various setups using symlinks, but in all cases, forge was not able to find minecraft and both jar and exe launchers couldn't find forge. So unless I'm linking the wrong files, I don't know why.

**Comment by P3rf3ctXZer0** [comment]
@TakunSho go with Technic - at least it works with Technic. Personally I manually distribute my pack as a multi-mic instance

**Comment by rheimus** [comment]
Closing as this is not really an issue with ServerSync.
