### ISSUE TITLE
Serversync Status Update

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [superzanti/ServerSync#121]
Just wondering @rheimus what the status of the project is or if it is still being worked on.

**Comment by rheimus** [comment]
I intend to do more work on the project during the holidays.

At the moment though my available time / energy is essentially zero, so the project is in hibernation.

I am happy to provide support for current functionality and fix low hanging bugs, major features will either need to wait or be pull requests from interested users.

**Comment by P3rf3ctXZer0** [comment]
Mainly just wondering when the core file checker will get that upgrade. Right now in its current state, the mod is somewhat unusable because the file comparison algorithm is not able to check 256 characters and any file exceeding folder path and file names cause the checker to flip out and stall.

**Comment by rheimus** [comment]
Interesting, sounds like SS is hitting file system limitations for you. Out of curiosity what system are you running?

There's probably some kind of hackaround possible in Java, will have to brush up on JIO.

**Comment by P3rf3ctXZer0** [comment]
Windows 10

**Comment by rheimus** [comment]
If you like heavily nested file structures you might be interested in this: 
https://www.howtogeek.com/266621/how-to-make-windows-10-accept-file-paths-over-260-characters/

However, ideally I should be able to find a solution in SS itself that does not require users to fiddle with their system.

**Comment by P3rf3ctXZer0** [comment]
That sounds great for certain things. Only issue is it does not help people who are not tech savvy like us 🗡 : D
