### ISSUE TITLE
Mod Spams Console, No Startup

### ISSUE THREAD

**Issue by PLKids** [superzanti/ServerSync#126]
#### Serversync Version: 
2.6.15
#### Minecraft Version: 
1.12.2
#### Issue:
Mod spams console and prevents server from starting up.
Please ask for any other necessary information. I'm not sure what else I need to provide. (I'm not that great at modding.)
This might be a duplicate of #59, I'm not sure. Any help is appreciated.
[latest.log](https://github.com/superzanti/ServerSync/files/2828562/latest.log)

**Comment by PLKids** [comment]
You can close this. I had to change the port to one not used by the host or the server. Thanks!

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by rheimus** [comment]
Awesome, nice work finding the issue!
