### ISSUE TITLE
Null Exception Warning

### ISSUE THREAD

**Issue by kmiller9292** [superzanti/ServerSync#127]
#### Serversync Version: 
2.6.21
#### Minecraft Forge:
14.23.1.2555
#### Minecraft Version: 
1.12.2
#### Issue: 

```
Loading language file: en_us
No language file available for: en_us, defaulting to en_US
{UPDATE=941250d6bec9349c10d694fca1c5d3e5be3a7fb8, UPDATE_NEEDED=0b561522ac51b055b1023f3efc52e2716c82643f, UPDATE_GET_SYNCABLE_DIRECTORIES=a83bd591c80b4b4cfcc8ef45f1244f3a8bc93aa3, UPDATE_GET_CLIENT_ONLY_FILES=bef08bcbf70a36a2cc145ddf77b964d5f88efdac, FILE_GET_CONFIG=3ac62fb6b5d30d3f0185d261aead03a91b6f07e9, FILE_GET_LIST=5a525af134d486cc482bc89f3c1afa09d5bd5ad0, FILE_COMPARE=b091b0c55cb79d606390f4fb731dcb0a4247b252, FILE_EXISTS=9ce83956360f34f8ffe4070683578c8f62e871f4, HANDSHAKE=37152bdde5c3e9e57a9025fb5db56c1eb45cbbd4, INFO_LAST_UPDATE=3d74c9cb7829397c877ca2d115c5b80714f9c95a, INFO_GET_FILESIZE=de50f5fb2b24c569e9c551550dbb480677a800ac, EXIT=44232a368542ee21c8917e309cd6ac0191f61971}
File: serversync-client.log not recognized as a minecraft mod (not a problem)
Exception in thread "Client processing" java.lang.NullPointerException
    at com.superzanti.serversync.filemanager.FileManager.getConfigurationFiles(FileManager.java:84)
    at com.superzanti.serversync.client.ClientWorker.getClientFiles(ClientWorker.java:97)
    at com.superzanti.serversync.client.ClientWorker.run(ClientWorker.java:243)
    at java.lang.Thread.run(Unknown Source)
```

# Client Config File

```
general {
    B:REFUSE_CLIENT_MODS=false
}

serverconnection {
    S:SERVER_IP=xxxxxxxxx

    I:SERVER_PORT=7345
}

rules {
    S:CONFIG_INCLUDE_LIST <
        config
    >

    S:FILE_IGNORE_LIST <
    >
}

misc {
    S:LOCALE=en_US
}

```

# Server Config File

```
general {
    B:PUSH_CLIENT_MODS=true
}

serverconnection {
    I:SERVER_PORT=7345
}

rules {
    S:CONFIG_INCLUDE_LIST <
    >

    S:DIRECTORY_INCLUDE_LIST <
        mods
        clientmods
    >

    S:FILE_IGNORE_LIST <
        serversync-2.6.21.jar
        LuckPerms-Sponge-4.1.61.jar
    >
}

misc {
    S:LOCALE=en_US
}

```

#### Server Logs

> [00:59:37] [Server client listener/INFO] [STDOUT]: [com.superzanti.serversync.util.Log:add:37]: LOG:Connection established with Socket[addr=/xxxxxxxxxxxxx,port=52040,localport=7345]Mar 2, 2019 12:59:37 AM
> [00:59:37] [Server client listener/INFO] [STDOUT]: [com.superzanti.serversync.util.Log:add:37]: LOG:[mods]
> [00:59:37] [ClientThread - /69.115.247.56/INFO] [STDOUT]: [com.superzanti.serversync.util.Log:add:37]: LOG:Recieved message from: /xxxxxxxxxxxxxxx
> [00:59:37] [ClientThread - /69.115.247.56/INFO] [STDOUT]: [com.superzanti.serversync.util.Log:add:37]: LOG:Sending coms messages
> [00:59:37] [ClientThread - /69.115.247.56/INFO] [STDOUT]: [com.superzanti.serversync.util.Log:add:37]: LOG:Recieved message from: /xxxxxxxxxxxxxx
> [00:59:37] [ClientThread - /69.115.247.56/INFO] [STDOUT]: [com.superzanti.serversync.util.Log:add:37]: LOG:Sending list of syncable directories: [mods]
> [00:59:37] [ClientThread - /69.115.247.56/INFO] [STDOUT]: [com.superzanti.serversync.util.Log:add:37]: LOG:Closing connection with: Socket[addr=/xxxxxxxxxxxxxxx,port=52040,localport=7345]
> [00:59:47] [Timer-1/INFO] [STDOUT]: [com.superzanti.serversync.util.Log:add:37]: LOG:Client connection timed out, closing Socket[addr=/xxxxxxxxxxxxxx,port=52040,localport=7345]

**Comment by rheimus** [comment]
Thank you for the detailed report! 👍.

Is this issue constant, or just happens occasionally?

The logs suggest that it is throwing null when attempting to get the number of files in the config directory, however, I can not reproduce the error in a test environment.

**Comment by rheimus** [comment]
Off topic note:
You probably don't want clientmods in the directory include list. With push client mods on this will most likely sync that directory twice. Once as client only mods and once as normal mods.

**Comment by rheimus** [comment]
Closing as this has had no traction.
