### ISSUE TITLE
Some folders in the Minecraft config folder do not sync

### ISSUE THREAD

**Issue by DuplexMinotaur9** [superzanti/ServerSync#129]
#### Serversync Version: 
2.6.17

#### Minecraft Version: 
1.7.10

#### Issue: 
When I sync with my server all of the mods sync just fine but some of the folders in the config folder don't sync. It seems to be only a few of the folders like the AM2 folder for Ars Magica 2 and the bbm folder for the Voltz Engine. Because it isn't syncing the config files in those folders the game generates new config files when launched which are different from the ones on the server so people are unable to join.

<details>
<summary>Configuration of ServerSync on Server</summary>
<pre>
# Configuration file

general {
    B:PUSH_CLIENT_MODS=true
}

serverconnection {
    I:SERVER_PORT=38067
}

rules {
    S:CONFIG_INCLUDE_LIST <
        config/**
    >

    S:DIRECTORY_INCLUDE_LIST <
        mods
        config
    >

    S:FILE_IGNORE_LIST <
        mods/AIImprovements-1.7.10-0.0.1b8.jar
        mods/AdminCommandsToolbox-0.0.2a_1.7.10.jar
        mods/Born-in-a-Barn-1.7.x.jar
        mods/forgeessentials-1.7.10-1.4.4.1187-server.jar
        mods/Morpheus-1.7.10-1.6.21.jar
        mods/Opis-1.2.5_1.7.10.jar
        mods/MobiusCore-1.2.5_1.7.10.jar
        mods/ServerTools-CORE-1.7.10-2.2.0.79.jar
        mods/TickDynamic-1.7.10-0.1.5.jar
        mods/worldedit-forge-mc1.7.10-6.1.1-SNAPSHOT-dist.jar
    >
}

misc {
    S:LOCALE=en_US
}
</pre>
</details>

**Comment by rheimus** [comment]
Try removing:
```
config/**
```

From your config include list. Would not be terribly surprised if the system is getting confused as the current configuration there is using both a blacklist and a whitelist for the config directory.

Adding config to directory include tells the system to include all of the files in config.

Adding patterns to config include tells the system to 'only' include these files.

Alternatively you could add the glob pattern 'match anything' to your config include list like so:
```
    S:CONFIG_INCLUDE_LIST <
		**/*
    >
```

----
Aside:
I would be cautious about blanket syncing all configuration files though, some of these files can be configured on a per user basis and it may end up annoying your players if their settings get swatted every time they sync with the server.
