### ISSUE TITLE
Request seperate client and server mods for serversync

### ISSUE THREAD

**Issue by DPxKnightxZero** [superzanti/ServerSync#13]
@superzanti I request that you split the mod it two segments server and client because I have a feeling there is a different issue at hand here. I am not sure if its a good idea that both client an sever use the same settings especially since they contain different functionality can you please separate them so I can see what each side of the mod does? It would help a lot with debugging and such. Also this issue is back.
![2015-06-10_16 15 20](https://cloud.githubusercontent.com/assets/10351221/8094322/eeb51c86-0f8b-11e5-8e54-7436af9db6df.png)

**Comment by DPxKnightxZero** [comment]
I think something with the client and server interaction is preventing the client from downloading things server side. Using your latest client 2.2.1 (I added the 1 to prevent issues with version checking)

**Comment by superzanti** [comment]
You MUST replace both server and client to 2.2.1

In it's current state the server cannot update the serversync.jar

This is not a problem with it being the same mod.

I'm closing this issue due to it being a duplicate, Please keep the same issues in the same threads.

**Comment by DPxKnightxZero** [comment]
I do ... trust me just talk to forge essentials team its better to have separate pieces.

**Comment by superzanti** [comment]
I have a different view than them.
