### ISSUE TITLE
Fabric Server Support

### ISSUE THREAD

**Issue by dh47** [superzanti/ServerSync#135]
Just wanting to know if there is suppor for the Fabric server or if theres a way to get it to work with it?

**Comment by rheimus** [comment]
ServerSync is a completely standalone process. You can use it with anything see: [WIKI](https://github.com/superzanti/ServerSync/wiki)

There is no specific support for fabric starting SS, though if you are a fabric developer it would probably be relatively simple to do the same as what the current forge support does, which is to start the SS process during server load. See: [ForgeLoader](https://github.com/superzanti/ServerSync/blob/master/src/main/java/com/superzanti/serversync/forgeloader/ForgeLoaderNET.java)
