### ISSUE TITLE
Why ServerSync is very important

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [superzanti/ServerSync#137]
Summery 

I do not think that ServerSync is only good for Minecraft and I whole heartedly believe it needs to exist - Right now there is no way to host files on a server and sync them to clients. The only ways to do this are very painful and are not common user friendly. @rheimus I can seldom say this but I think you should consider making this a more open project and also remind people before using ServerSync to make sure that all clients have proper Antivirus and Firewall Security. Maybe make a warning label on box. Also you could say "Warning make sure you know the source you are rquesting files from." Even though #128 sounds like a great idea I have a bad feeling that if you don't focus on the following features below this will never fully get its wings off the ground.

* ServerSide Speed Upload Control - Servers should say how fast they can transfer something

* MD5 Hash Log for Folders files etc - However the application is currently detecting files seems glitchy at best.

* More Socket Throughput - Allow the server to determine concurrent users. Seems right now SS cuts off at 3 users at a time.

* Write a disclaimer - This needs to be done if ServerSync gains notoriety. The Main Reason is people are always way to good at finding ways to cheat and if someone did something illegal like with file sharing etc you should not let yourself be vulnerable to legal recourse.

* Keep it open and free - There are no good free easy to use alternatives to do what this application does. It is the last bastion of not being forced to use a damn cloud service. I have looked and the closest thing I can find is solder which is not noob friendly. Your application is a jack knife because essentially although it has the potential to the solution for modpack devs. It is actually good for file synchronization in general. Essentially - this now in my arsenal for 2 other servers I host with mods - 7 Days to Die and Staxel.

* The Project should not be strictly Minecraft - Lets face it you have stumbled onto the Triforce. Many people including myself who are working on a project and need to keep files synced benefit from this. I think saying this is strictly Minecraft is an injustice.

I hope these reasons inspire you to continue to understand that this project is not only important to modpack devs but dev teams that need an easy file share and synchro solution alone.

**Comment by rheimus** [comment]
Thanks for the feedback 😊.

You have some great points here. I had thought that SS was already under a license but apparently not, I've fixed this.

SS already has a disclaimer everywhere that it is officially available that advises people to be careful when connecting to unknown servers.

**Comment by rheimus** [comment]
#128 Is interesting, though I am really not keen on hackjobing virus scanning when users can get much better solutions themselves via free or paid services/products.

**Comment by rheimus** [comment]
> The Project should not be strictly Minecraft
This has been the core purpose of SS for a while, there is some Minecraft specific loader code but SS itself has no dependency on Minecraft or Forge. I used it to sync two computers at work once when I got super lazy 😂

**Comment by P3rf3ctXZer0** [comment]
I mean I am whole heartedly glad to see you appreciated all my feedback. I really enjoy testing and breaking things for you :D
