### ISSUE TITLE
Mods (.jar) do not update properly

### ISSUE THREAD

**Issue by superzanti** [superzanti/ServerSync#14]
Currently I am aware of a bug that does not allow files to be updated.

Files can be added and deleted just fine, but when it comes to updating a given mod, it does not work due to the mod being in use by java. I get around this in deletion by executing a 'deleteOnExit'

I'm working on a function to do this same kind of thing for updating. Stay tuned and please refrain from starting new issues that are duplicates of this.

**Comment by DPxKnightxZero** [comment]
@superzanti thank you very much for taking your time to polish the mod. Anything you do is very much appreciated.

**Comment by DPxKnightxZero** [comment]
@superzanti you know you keep saying download file from your git hub but your release folder always is blank which is confusing. So where exactly do you keep all the modified releases?

**Comment by DPxKnightxZero** [comment]
@superzanti this is an example of "files on github" https://github.com/CannibalVox/DimDoors/releases 
Here is your folder with files on git hub. https://github.com/superzanti/ServerSync/releases

**Comment by superzanti** [comment]
https://github.com/superzanti/ServerSync/tree/master/build/libs

I've linked that 3 times now. Please bookmark the link if you must.

The build folder is the most common build location.

**Comment by DPxKnightxZero** [comment]
Question why is there 2.2 and 2.3 which one is newest?

**Comment by superzanti** [comment]
Guess.

**Comment by superzanti** [comment]
Issue completely fixed in 2.4 but could cause issues if a user decides not to restart after the update. In the future I will force the user to restart after updates.
