### ISSUE TITLE
Client times out when ignoring too many files.

### ISSUE THREAD

**Issue by slidedrum** [superzanti/ServerSync#144]
#### Serversync Version: 
2.6.17
#### Minecraft Version: 
1.12.2
#### Issue: 
When ignoring too many files, it takes too long to print "ignoring whatever file" and does not respond to the server, causing it to time out.  I am using multiple mods that have folders inside the mods folder.  Naimly, [Millenaire](https://millenaire.org/) and [OTG (Biome Bundle)](https://www.curseforge.com/minecraft/mc-mods/open-terrain-generator) I can chose to not ignore them, and then it syncs as normal and proceeds to delete them. Which is not terrible as it does auto generate them when missing.  But it is completely unnecessary and wastes time.  It is my understanding that if you do not print them out to the log it will go significantly faster.  Also, adding a folder ignore feature from #142 would probably also fix the issue.  As just printing out "ignoring millenaire folder" would be fine.  Could we please get a client option to reduce logging to just show files that are actually being downloaded or deleted?   I can provide a client or server log if you want, but it's just going to list a crapload of ignored files, and then say timed out.  If you would like to reproduce, just create an installation with Millenaire and Biome Bundle, and try to sync it while ignoring the Millenaire and OTG folders on the client.  Thank you for your time.
<details>
<summary>Client config</summary>
<pre>

[serversync-client.cfg](https://github.com/superzanti/ServerSync/files/4174662/serversync-client.txt)
</pre>
</details>

**Comment by rheimus** [comment]
Give the latest release a try: https://github.com/superzanti/ServerSync/releases.

Does not appear to take much time when ignoring millenaire.

**Comment by rheimus** [comment]
3.0 Changed the way timeouts work on the server. It may solve this issue.

**Comment by P3rf3ctXZer0** [comment]
I will run tests immediately.

**Comment by rheimus** [comment]
Probably related to #160

**Comment by rheimus** [comment]
Closing this for now as 3.x.x has major changes to the server code.
