### ISSUE TITLE
Mod cannot be loaded Forge version to new

### ISSUE THREAD

**Issue by Lice2** [superzanti/ServerSync#150]
#### Serversync Version: 
serversync-3.0.0
#### Minecraft Version: 
1.14.4 Forge Version 28.2.0
#### Issue: 
The mod cannot be loaded because the current Forge version is too new.
The error message only comes from the client
<details>
<summary>Logs (serverysync & minecraft)</summary>
<pre>

</pre>
</details>

**Comment by rheimus** [comment]
Sigh, looks like forge has changed their mod loading API... again.

You can still run serversync without forge loading the server though, I'll look into making a third loader that works with whatever their latest loading code is.

https://github.com/superzanti/ServerSync/wiki has instructions on starting ServerSync without forge.

**Comment by rheimus** [comment]
Yep looks like the way mods tie into the forge lifecycle has changed.

It's all still under the same package name though so it looks like I'm going to have to create a separate mod that acts as a proxy for loading ServerSync specifically for 1.14 onwards.

**Comment by rheimus** [comment]
There is now a forge loader mod for 1.13+, though I would only recommend using it if you host your own server and don't use a third party for now. Need to work around hosts being twitchy with spawned processes.
