### ISSUE TITLE
Unable to send configs to client - This can and will be a huge issue if not dealt with.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [superzanti/ServerSync#151]
#### Serversync Version: 
3.0.0.

#### Minecraft Version: 
1.15.2
#### Issue: 
Unable to send config files.

File Tree of Files I am trying to sync https://gist.github.com/P3rf3ctXZer0/b009d307de431597c254ba3d429ef923

Serverside Config https://gist.github.com/P3rf3ctXZer0/ed7064c9b4bc00b0a2140525a72fd02c

Client Config https://gist.github.com/P3rf3ctXZer0/3edb0439d0a7d62c969960d7c85e291d

[serversync-client.log](https://github.com/superzanti/ServerSync/files/4332492/serversync-client.log)

Serversync-server log https://gist.github.com/P3rf3ctXZer0/c41f4e72b2366596df34e18c05f07368

**Comment by P3rf3ctXZer0** [comment]
Nothing I do sends the config files.

**Comment by rheimus** [comment]
Yep looks like the config include list is being ignored by the server.

Shall pick this up next as config whitelist is a good feature to have.

**Comment by rheimus** [comment]
Fixed the config include functionality in #153

The include list still needs a rework to be more user friendly, however, it will work as it did before now. 

In your server config above you will need to remove the leading 'config/' from your files listed in the config include list as it assumes that it is rooted in the 'config' directory.

**Comment by P3rf3ctXZer0** [comment]
I will start testing immediately.

**Comment by P3rf3ctXZer0** [comment]
this works kind of. 

Thanks to windows 10 partially blocking the exe users would have to unblock exe and too many people spook easily to listen to basic instruction. the only way to get around it is to hook into forge.

I will keep trying to fix file permissions. As well as test things for you.
