### ISSUE TITLE
Serversync has an issue downloading large amounts of mods

### ISSUE THREAD

**Issue by DPxKnightxZero** [superzanti/ServerSync#16]
My players are reporting that after a bit the download application stops responding. I cannot 100% confirm this but a way to relieve stress may be to add a more accurate loading screen rather than just the %. 

Maybe Overall = %
Mod = %
Mod Size = int in KB
Estimated Time Remaining = Numerical Indication
Estimated Download Speed = int in mb

**Comment by superzanti** [comment]
Sorry, I will not add this.
Adding progress-bars adds a lot of overhead that I'm not willing to have in this application.

I will however accept a pull request if the code isn't too bloated.

**Comment by DPxKnightxZero** [comment]
What do you mean?

**Comment by superzanti** [comment]
I'm saying I will not do it, but someone else can.
