### ISSUE TITLE
Issue with Gradle and Eclipse

### ISSUE THREAD

**Issue by kernel-pan-ic** [superzanti/ServerSync#162]
I'd like to load this project into Eclipse, and I've done as the README says, but after running `./gradlew eclipse` it tells me that there's no such task. The exact output is as follows: 
```
[ServerSync]$ ./gradlew eclipse

FAILURE: Build failed with an exception.

* What went wrong:
Task 'eclipse' not found in root project 'ServerSync'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 503ms
```
I'm not at all familiar with the Gradle build system, so any help would be appreciated.

**Comment by rheimus** [comment]
>.< I probably offhand deleted the eclipse setup task. I'll add it back in.

For now though you can fix it by adding eclipse to the list of plugins in the build.gradle file.
```
plugins {
  ...
  id 'eclipse'
}
```

or by using something like buildship: https://marketplace.eclipse.org/content/buildship-gradle-integration which is what I used when I was still using Eclipse on this project.

**Comment by rheimus** [comment]
Updated the project to include the Eclipse plugin. Should work as described in the readme now, feel free to reopen if it does not.
