### ISSUE TITLE
ServerSync can not save IP addresses and port numbers

### ISSUE THREAD

**Issue by HaibaraGT** [superzanti/ServerSync#169]
#### Issue: 

<details>
Thank you very much for developing such a useful tool, but ServerSync cannot automatically save the IP address and port number during use. I want it to save automatically. thank.

At the same time, I translated the language files into Chinese. Can I consider adding them to the tool?
[MessagesBundle_zh_CN.zip](https://github.com/superzanti/ServerSync/files/4398931/MessagesBundle_zh_CN.zip)

</details>

**Comment by rheimus** [comment]
Yeah, I can add these manually or you can set up a pull request.

**Comment by HaibaraGT** [comment]
> Yeah, I can add these manually or you can set up a pull request.
I tried to add the address to the configuration file, but found that ServerSync could not display the GUI after the modification。
This is the serversync configuration file for my MC client. After using it, I did not start serversync.

[serversync-client.zip](https://github.com/superzanti/ServerSync/files/4402546/serversync-client.zip)

**Comment by rheimus** [comment]
Looks like your configured port is outside the range that ServerSync accepts.

Not really sure why but it is configured to have a maximum of 49151.

I'll change this at some point, for now are you able to assign a port between 1-49151?

**Comment by rheimus** [comment]
Added your translations, they will be in version 3.4.0+

I did just recently add some more client strings though, might be worth reviewing them if you are interested.

**Comment by rheimus** [comment]
Added a config save after sync with a server.

This should save the last used address for the next time you open ServerSync.

Files available here if you want early access to it: https://github.com/superzanti/ServerSync/actions/runs/67269237

**Comment by HaibaraGT** [comment]
> Added a config save after sync with a server.
> 
> This should save the last used address for the next time you open ServerSync.
> 
> Files available here if you want early access to it: https://github.com/superzanti/ServerSync/actions/runs/67269237

I changed the port and now he can start. At the same time, the 3.4.0 version can also automatically save the updated IP address and port.

Thank you

**Comment by rheimus** [comment]
Closing as task complete
