### ISSUE TITLE
Update clients automatically with ServerSync and HMCL.

### ISSUE THREAD

**Issue by HaibaraGT** [superzanti/ServerSync#176]
#### Issue: 

<details>
Dear developer, I looked at the automated commands section on ServerSync. Now I want to use the HMCL launcher with ServerSync to update the client automatically, but I haven't found a way to achieve this. Can you tell me how to do this?

HMCL link：https://hmcl.huangyuhui.net/download
</details>

**Comment by rheimus** [comment]
I am unable to access the linked URL. Is it perhaps behind some kind of regional firewall?

I am unfamiliar with the program in question so I can provide no support for it, the steps should be the same for the most part as the MultiMC setup.

Hook into the 'before minecraft starts' event and run ServerSync with the `silent` or `progress-only` argument.

**Comment by HaibaraGT** [comment]
> I am unable to access the linked URL. Is it perhaps behind some kind of regional firewall?
> 
> I am unfamiliar with the program in question so I can provide no support for it, the steps should be the same for the most part as the MultiMC setup.
> 
> Hook into the 'before minecraft starts' event and run ServerSync with the `silent` or `progress-only` argument.

Sorry,I did not consider the connection problem, this is the link of HMCL on Github.
https://github.com/huanghongxun/HMCL.
Take a look

**Comment by EnterFor** [comment]
It would be great to support HMCL. This is a game starter developed by Chinese developers

**Comment by 1636578433** [comment]
i hope the serversync can support HMCL too.

**Comment by rheimus** [comment]
@1636578433 The variable $INST_JAVA is probably only available in MultiMC. I am not sure if HMCL has an equivalent.

What that is trying to do is run this command: `java -jar serversync-3.5.1,jar progress-only`, the `$INST_JAVA` is linking to the instance of the JVM that MultiMC is using for that specific Minecraft instance.

**Comment by 1636578433** [comment]
https://cdn.discordapp.com/attachments/488019168986136586/698754418753011742/modd.PNG

I don't know why HMCL can't find(i put the serversync in correct folder) and if change to .exe i can't open it.

**Comment by HaibaraGT** [comment]
> @1636578433 The variable $INST_JAVA is probably only available in MultiMC. I am not sure if HMCL has an equivalent.
> 
> What that is trying to do is run this command: `java -jar serversync-3.5.1.jar progress-only`, the `$INST_JAVA` is linking to the instance of the JVM that MultiMC is using for that specific Minecraft instance.
> 
> If you are on windows you could also try the .exe package like so `ServerSyncClient.exe progress-only`

I asked this question in the HMCL community, HMCL developers said that they will support the use of $ INST_JAVA in future versions. And deal with the "file not found" problem.

Thanks to the efforts of the serversync developers, this issue can be closed.

**Comment by 1636578433** [comment]
OK,thank for your help!

**Comment by Creepercdn** [comment]
> https://cdn.discordapp.com/attachments/488019168986136586/698754418753011742/modd.PNG
> 
> I don't know why HMCL can't find(i put the serversync in correct folder) and if change to .exe i can't open it.

Just change command is `cmd /c "start /wait ServerSyncClient.exe -xxxxxxxx"`
