### ISSUE TITLE
Error Freezes

### ISSUE THREAD

**Issue by kaiserdj** [superzanti/ServerSync#177]
#### Issue: 
It freezes without doing anything until the timeout expires, and it doesn't finish syncing all the files

![image](https://user-images.githubusercontent.com/5487950/78568290-2dbfff00-7822-11ea-8e7d-6d1282fa40ba.png)

[serversync-server.log](https://github.com/superzanti/ServerSync/files/4439055/serversync-server.log)
[serversync-server-connection-from--127-0-0-1.log](https://github.com/superzanti/ServerSync/files/4439056/serversync-server-connection-from--127-0-0-1.log)
[serversync-client.log](https://github.com/superzanti/ServerSync/files/4439057/serversync-client.log)

**Comment by rheimus** [comment]
Seem's to have died while trying to fetch the file size of one of the files. Unfortunately my logging is garbage there 😂 I don't log which file it was trying to work on. Will have to fix that.

**Comment by rheimus** [comment]
Early test files can be found here: https://github.com/superzanti/ServerSync/actions/runs/72526484

Latest changes include some basic "File went missing" handling for the server, it is not great at the moment as it will just send a 0 byte file to the client and log an error to the server owner.

**Comment by kaiserdj** [comment]
I have tried it and it has not given me any error, thank you very much ❤️

**Comment by rheimus** [comment]
Closing, changes are included in release 3.5.0
