### ISSUE TITLE
Character encoding

### ISSUE THREAD

**Issue by kaiserdj** [superzanti/ServerSync#181]
#### Issue: 
Characters are not showing well
I think the UTF-8 character encoding may not be applied

It should put: Dirección IP
![image](https://user-images.githubusercontent.com/5487950/78669876-37f30380-78dd-11ea-9d4c-09a059b4d68c.png)

*Sorry for putting so many issues 😅 ❤️

**Comment by rheimus** [comment]
Issues are good, I would be worried if there were none 😊.

**Comment by rheimus** [comment]
This should hopefully be solved when I add a custom control for ResourceBundle loading.

Alternatively, I could force a requirement of java 9+

Out of curiosity what java version are you running?

**Comment by kaiserdj** [comment]
My current java version:
```
> java -version
java version "1.8.0_241"
Java(TM) SE Runtime Environment (build 1.8.0_241-b07)
Java HotSpot(TM) 64-Bit Server VM (build 25.241-b07, mixed mode)
```

**Comment by rheimus** [comment]
Closing as current translations have been converted to an ascii format that should work.
