### ISSUE TITLE
Feature suggestions

### ISSUE THREAD

**Issue by HaibaraGT** [superzanti/ServerSync#188]
#### Issue: 

<details>
Feature suggestions：

Hello developer, when using ServerSync, I noticed that sync files are scanned file by file. So is it possible to use the file fingerprint list to achieve this process? In this way, I think it reduces the network expenditure and at the same time speeds up the file comparison speed, especially when there is no update.
The specific ideas are as follows:
The server scans the files to be synchronized (according to the configuration file) and generates a file fingerprint list, which can reflect whether the file has been changed.
The client first downloads this file list from the server, and then compares the client against the file list. After finding a file that is inconsistent with the file list, go to download and replace this file.

Of course, this is just my idea, not clear whether it can be achieved. Thank you.

</details>

**Comment by rheimus** [comment]
I am intending to build a "mode 2" sync which behaves mostly the way you described. This will be available for server admins to turn on if they wish.

**Comment by HaibaraGT** [comment]
> I am intending to build a "mode 2" sync which behaves mostly the way you described. This will be available for server admins to turn on if they wish.

It's great, but I don't write code, I can only provide some suggestions. And assist in testing >_<

**Comment by rheimus** [comment]
Closing this as it is covered in other tasks.
