### ISSUE TITLE
Server lag severely when serversync client syncing fails

### ISSUE THREAD

**Issue by RisingInIris2017** [superzanti/ServerSync#189]
#### Serversync Version: 
3.5.1.0
#### Minecraft Version: 
1.12.2
#### Issue: 

<details>
<summary>Logs (serverysync & minecraft)</summary>
Serversync Logs:

Client:

https://github.com/superzanti/ServerSync/files/4503012/serversync-client.log

Server:

https://github.com/superzanti/ServerSync/files/4503013/serversync-server-connection-from--58-22-113-13.log

Minecraft Server Log:

https://github.com/superzanti/ServerSync/files/4503014/2020-04-20-1.log
</details>

My IP address is `58.22.113.13`, and you will find that I used [Spark](https://github.com/lucko/spark)
to test my server's TPS before and after I attempted to sync my file from my server with Serversync.

You will find that before my attempt the server's TPS is 20.0, but after it dropped to below 10.
At the same time my server syncing is failed. It stuck at 9% point.

If server could recover from clients' failed trying of syncing, it may be better.
But after the TPS dropped, it never recovered, just kept low and I had to stop server manually.

I think it is good to report this issue to you.
Thanks for your help in advance!

**Comment by HaibaraGT** [comment]
> #### Serversync Version:
> 3.5.1.0
> 
> #### Minecraft Version:
> 1.12.2
> 
> #### Issue:
> Logs (serverysync & minecraft)
> Serversync Logs:
> Client:
> 
> https://github.com/superzanti/ServerSync/files/4503012/serversync-client.log
> 
> Server:
> 
> https://github.com/superzanti/ServerSync/files/4503013/serversync-server-connection-from--58-22-113-13.log
> 
> Minecraft Server Log:
> 
> https://github.com/superzanti/ServerSync/files/4503014/2020-04-20-1.log
> 
> My IP address is `58.22.113.13`, and you will find that I used [Spark](https://github.com/lucko/spark)
> to test my server's TPS before and after I attempted to sync my file from my server with Serversync.
> 
> You will find that before my attempt the server's TPS is 20.0, but after it dropped to below 10.
> At the same time my server syncing is failed. It stuck at 9% point.
> 
> If server could recover from clients' failed trying of syncing, it may be better.
> But after the TPS dropped, it never recovered, just kept low and I had to stop server manually.
> 
> I think it is good to report this issue to you.
> Thanks for your help in advance!

I looked at the server logs and found that you loaded serversync in the form of a mod. In fact, it is not recommended to do so. It is recommended that you run serversync alone to observe whether this problem will occur.

**Comment by rheimus** [comment]
The server should have a built-in timeout that will disconnect clients when they are unresponsive, I would be surprised if it used much processing power at all when idle though.

You could potentially assign more memory to your server, though ideally, ServerSync runs in its own process so that you can control exactly how much resource it is allowed to use. 

@RisingInIris2017 Do you have the spark logs/report available?

**Comment by rheimus** [comment]
I am going to close this as there have been several major changes.

Please raise another issue if this is still a problem.
