### ISSUE TITLE
Help Request - How do I add custom images to custom main menu?

### ISSUE THREAD

**Issue by DPxKnightxZero** [superzanti/ServerSync#19]
I noticed you had those sweet button textures how did you add them to your buttons. I have gathered I open the custom main menu jar and open assets/custommainmenu/textures then make your own folder and add a custom png but beyond that I am confused.

**Comment by DPxKnightxZero** [comment]
This is how my config is made. I only copied the part that is relevant. 
 "buttons":
    {
        "Server Synchronization":
        {
            "text" : "Server Synchronization",
            "image" : "custommainmenu:textures/gui/DPGLogo.png",
            "posX" : -100,
            "posY" : 24,
            "width" : 200,
            "height" : 20,
            "action" : 
            {
                "type" : "openGui",
                "gui" : "connectToServer"
            }
        },

**Comment by superzanti** [comment]
CustomMainMenu is not my mod, it's another mod. Google it and you should be able to find it pretty easily.

**Comment by DPxKnightxZero** [comment]
Oh i just figured you would know how to use it sorry for bothering you.
