### ISSUE TITLE
Serversync not ignoring files

### ISSUE THREAD

**Issue by Alkiasan** [superzanti/ServerSync#192]
#### Serversync Version: 
3.5.1
#### Minecraft Version: 
1.14.4
#### Issue: 
Added Optifine.jar to my mods folder as a test, and disabled it from being synced inside of the server's config file, but for some reason, Serversync consistently deletes it.

![image](https://user-images.githubusercontent.com/62717881/83204473-d82e1180-a143-11ea-92d2-c15ab9e12dc7.png)
Above image states that there are no ignored files.
![image](https://user-images.githubusercontent.com/62717881/83204504-ea0fb480-a143-11ea-8923-cbf8d5897a3e.png)
Above image is Serversync's logs deleting the file.
![image](https://user-images.githubusercontent.com/62717881/83204645-3ce96c00-a144-11ea-9ef6-c33b7e1d8e4b.png)
Above image is the serverside config. Trying both / and \ just in case i'm being dumb.

**Comment by HaibaraGT** [comment]
> #### Serversync Version:
> 3.5.1
> 
> #### Minecraft Version:
> 1.14.4
> 
> #### Issue:
> Added Optifine.jar to my mods folder as a test, and disabled it from being synced inside of the server's config file, but for some reason, Serversync consistently deletes it.
> 
> ![image](https://user-images.githubusercontent.com/62717881/83204473-d82e1180-a143-11ea-92d2-c15ab9e12dc7.png)
> Above image states that there are no ignored files.
> ![image](https://user-images.githubusercontent.com/62717881/83204504-ea0fb480-a143-11ea-8923-cbf8d5897a3e.png)
> Above image is Serversync's logs deleting the file.
> ![image](https://user-images.githubusercontent.com/62717881/83204645-3ce96c00-a144-11ea-9ef6-c33b7e1d8e4b.png)
> Above image is the serverside config. Trying both / and \ just in case i'm being dumb.

You may need to put mods like optifine in the clientmods folder to avoid serversync deleting it.
Create a folder of folderclimods in the root directory of the server and put optifine.jar in it. Adjust the serversync configuration file

servser
     B: PUSH_CLIENT_MODS = true
clinet
    B: REFUSE_CLIENT_MODS = false

**Comment by rheimus** [comment]
Optifine is indeed one of the mods I had in mind when designing the clientmods feature.
https://github.com/superzanti/ServerSync/wiki/Client-Mods

Though it would seem that there might be a misunderstanding of the ignore list functionality here?

The ignore list for a server will define a list of files that exist on the server but will not be sent to the client (i.e. they are ignored by the server).

The ignore list for a client will define a list of file that exist on the client but will be ignored during the deletion phase (i.e. the client knows this file will not interfere with connecting to the server). This functionality was designed for clients to use their own favorite client side mods without the server needing to know about it.

**Comment by Alkiasan** [comment]
Ah, okay, yeah, I got the ignore list functionality wrong then.
Was hoping it was possible to stop the server from detecting certain mods without editing clientside, but in the end ended up just giving people modified clientside configs haha.
Thanks for the response ^^
