### ISSUE TITLE
Add a CLI argument to force set language

### ISSUE THREAD

**Issue by Creepercdn** [superzanti/ServerSync#197]
Add a CLI argument to force set language

| Name | Description | Example |
| ---- | ---- | ----|
| `-l`, `--lang` | Force set UI language | `java -jar serversync.jar -l zh-cn`|

**Comment by rheimus** [comment]
Added this in alpha 2 of 3.7.0. This will filter through to a proper release eventually.

Early access in my fork here:
https://github.com/rheimus/ServerSync/releases
