### ISSUE TITLE
Files missing after sync

### ISSUE THREAD

**Issue by Ceifeire** [superzanti/ServerSync#198]
#### Issue: Sometimes files fail to copy over when syncing

Sometimes when doing a sync some files get removed but the new version isnt populated in. Is there a way to ensure this doesnt happen? I have a large pack and missing any files is always hard to figure out

**Comment by HaibaraGT** [comment]
Hello, please use the latest version of ServerSync. The new version solves many problems.

**Comment by Ceifeire** [comment]
According to curse that is the latest 1.12.2 version. Or does your mod not care about the minecraft version since it runs on its own?

**Comment by HaibaraGT** [comment]
> 根据诅咒，这是最新的1.12.2版本。还是您的mod不在乎我的世界版本，因为它可以独立运行？

I see that you are using version 2.6.17, but the latest version is already 3.6.0. ServerSync can run without Minecraft. 3.6.0 still supports 1.12.2 to 1.16.2

**Comment by HaibaraGT** [comment]
> According to curse that is the latest 1.12.2 version. Or does your mod not care about the minecraft version since it runs on its own?

I see that you are using version 2.6.17, but the latest version is already 3.6.0. ServerSync can run without Minecraft. 3.6.0 still supports 1.12.2 to 1.16.2

**Comment by Ceifeire** [comment]
ok. I will update and see what happens.

**Comment by rheimus** [comment]
@Ceifeire ServerSync in it's recommended use works for any version.

There is mod loading code that starts SS for you when the forge environment starts, but I would generally not recommend using that.

**Comment by Ceifeire** [comment]
Are you referring to the client or the server? I was hoping there was a way to boot SS with minecraft. Is there a way to run the server SS without booting the server itself?

**Comment by HaibaraGT** [comment]
> Are you referring to the client or the server? I was hoping there was a way to boot SS with minecraft. Is there a way to run the server SS without booting the server itself?

Starting SS separately is the recommended method, you can check the wiki. SS can be started separately and works normally without starting the Minecraft server.

**Comment by Ceifeire** [comment]
ok. I will look into that more. I have come across a minor problem with the updated 3.6.0 version. This might be due to not running the sync server the recommended way but when the sync finished and starts the deletion process it gets hung up there and just sits indefinitely.

**Comment by rheimus** [comment]
@Ceifeire Can you attach the logs from a failed run? There may be a crash happening there.

**Comment by rheimus** [comment]
There is also a preview of the new manifest style of sync here:
https://github.com/superzanti/ServerSync/releases/tag/v3.7.0-alpha.1

Not that it is very much bleeding edge though, so it probably has issues of its own.

**Comment by Ceifeire** [comment]
Alright here are the logs. one for the server itself and one for the connection established by a player.

Server Log
https://pastebin.pl/view/2e0eb269

Player connection log
https://pastebin.pl/view/3cd710da

**Comment by rheimus** [comment]
```
LOG:Starting scan for managed configs: Sep 21, 2020
LOG:Include patterns: {
 
}
DEBUG:Failed to hash file: config
DEBUG:[sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
```

Interesting, looks like we might be trying to hash a directory. There is probably an issue in the file walker server side, though it should not stop the client from working.

**Comment by rheimus** [comment]
Closing this for now as the server code has had major changes for verson 3.x.x.
