### ISSUE TITLE
Questions on adding inclusive files such as such as mod created folders

### ISSUE THREAD

**Issue by DPxKnightxZero** [superzanti/ServerSync#2]
I have a few mods like better records and forge essentials that create there own folder trees and tend to make directories. I was wondering how I can transfer a file that is not in the mod or config folder.Also I was wondering if you could add custom folders to watch list and have them install in a different folder clientside when being downloaded. 

Example 
Server Root
Client only [folder tree]
      - [Client]-Optifine-Example.jar

**Comment by superzanti** [comment]
The mod transfers everything in the mods folder and the config folder (except what's ignored in the serversync.cfg). So even if they are in subdirectories they will sync.

**Comment by DPxKnightxZero** [comment]
In other words it does not detect changes in root of server 
[Server File Tree]
   - mods
   - libraries
   - config
   - my random ass folder here

**Comment by superzanti** [comment]
No not currently. But it's a very simple change in the source code to add it.

**Comment by DPxKnightxZero** [comment]
Thank you I would very much appreciate an exclude and include feature and cd install feature.

**Comment by superzanti** [comment]
What do you mean by 'change directory install'

**Comment by DPxKnightxZero** [comment]
Okay so when I make adjustments to server lets call it a client update from server I want to be able  to create a folder in the server called client-side mods which the server won't use but serversync can send to client and place in the client's mods; folder. Since I append file labels to mods such as [Server]-Mod name here [Client]-Mod Name Here and [Universal]-Mod name here it allows me to keep track of compatibility issues. Essentially my goal is to creating a self updating technic pack. That will not force my users to use stupid dropbox or copy.com. I figure I could achieve this using server-sync and custom main menu.

**Comment by superzanti** [comment]
This is something I leave up to the user to install and then add it to the 'ignored files' list in the config options.

This maybe a feature I add in the future, but not now.

**Comment by DPxKnightxZero** [comment]
Yeah I would just like it to work with the multiplayer button first XD

**Comment by superzanti** [comment]
It does. You are not assigning your button id correctly.

**Comment by DPxKnightxZero** [comment]
Where is latest file ...

**Comment by superzanti** [comment]
https://github.com/superzanti/ServerSync/blob/master/build/libs/serversync-2.2.jar

**Comment by superzanti** [comment]
I just updated but have not changed the version. I am at work so I cannot do testing at the moment. Would you mind testing the new version for me?

https://github.com/superzanti/ServerSync/blob/master/build/libs/serversync-2.2.jar

I still have it labeled 2.2 but I can assure you things have changed.

Get back to me on weather or not this fixes the issue.

**Comment by superzanti** [comment]
@DPxKnightxZero 
Do you still want this enhancement or can I close this issue?

**Comment by DPxKnightxZero** [comment]
Yes it will prevent future issues. If you don't mind the effort :)

**Comment by superzanti** [comment]
Can you explain it again in a different way?

**Comment by DPxKnightxZero** [comment]
Okay so think of this you want the client to always ignore lets use anything that looks like this; "[Server]-*" before downloading server sync will check the file name and see that it says; "[Server]-" "*" which means it will ignore any file starting with the characters [Server]- it will automate how it delegates file changes. Since I do have some server side only mods such as Forge essentials that tend to update as quickly as an hour.

**Comment by DPxKnightxZero** [comment]
No its fine.

**Comment by superzanti** [comment]
Okay.
