### ISSUE TITLE
Add updating for client side only mods

### ISSUE THREAD

**Issue by superzanti** [superzanti/ServerSync#20]
I want the server to be able to push new client-side-only mods to the clients.

**Comment by DPxKnightxZero** [comment]
Told you it would be helpful in the future. https://github.com/superzanti/ServerSync/issues/2

**Comment by Lordmau5** [comment]
Could be done by adding a "clientmods" folder on the server that get's sent checked with client-files perhaps?
E.g. "clientmods" on the server, and "mods/clientmods" on the client, since every sub-folder of the "mods" folder get's loaded.

**Comment by osum4est** [comment]
I agree!

**Comment by rheimus** [comment]
Have added this ability in 2a7af1d
