### ISSUE TITLE
UI For configuring client

### ISSUE THREAD

**Issue by rheimus** [superzanti/ServerSync#201]
It would be much more friendly for users to have a UI to configure ignored files and other such settings client side.

Prototype based on UWP
https://stackblitz.com/edit/ss-client-uwp-prototype

**Comment by Hadyark** [comment]
What do you think about 

- add button to edit/save "Ip adress" and "port"

- display a list of mods comparing the client version with that of the server. The user can then know which version will be updated. (Easier than looking in the logs)

**Comment by rheimus** [comment]
The address you are connecting to is one of the primary concerns for the client UI, it makes sense for the IP and Port fields to be always available rather than hidden behind clicks/menus.

A list of files is what I was thinking of yeah, basic spitball of a prototype here: https://stackblitz.com/edit/spitball-ss-client-config?file=src%2Fapp%2Fapp.component.html

**Comment by rheimus** [comment]
First pass UI available in v4, closing this.
