### ISSUE TITLE
How would Serversync work on a server running multiple instances of MC server?

### ISSUE THREAD

**Issue by InnerSanctuary** [superzanti/ServerSync#208]
#### Serversync Version: 
serversync-3.6.0.jar
#### Minecraft Version: 
1.12.2
#### Issue: 
Good Morning!

I am very excited finding your software and thank you for all your effort.  I am wondering how this sync works with multiple minecraft instances running on a server (all with different ports of course).  In other words, how do i modify your bat file to run server sync for all my kid's instances?>

Thank you!

<details>
<summary>Logs (serverysync & minecraft)</summary>
<pre>

</pre>
</details>

**Comment by rheimus** [comment]
The lazy start bat file is probably fine, you would just need to go into the config file for ServerSync and change which port it is serving on.

Likewise, for the client-side you would need to configure them to point at the appropriate port for whichever instance you want to connect to.

**Comment by rheimus** [comment]
e.g.
Minecraft instance 1 is serving on 1234
Serverysync instance 1 is serving on 1235

Minecraft instance 2 is serving on 2345
Serversync instance 2 is serving on 2346

etc

**Comment by rheimus** [comment]
Closing this for now, feel free to reopen if the question is unresolved.
