### ISSUE TITLE
Windows file deletion

### ISSUE THREAD

**Issue by superzanti** [superzanti/ServerSync#21]
On windows the files are never deleted. The mod is not used because it was overwritten, but it's never deleted.

**Comment by DPxKnightxZero** [comment]
Um I have not had this issue. ... are you sure it is an issue?

**Comment by superzanti** [comment]
Check the folder. If you remove a mod from the server, then on windows the file will not be deleted. However, the client will not use that mod anymore which is possibly why it seems like it's not an issue.

**Comment by DPxKnightxZero** [comment]
Aw that makes sense.

**Comment by Lordmau5** [comment]
Can be fixed by making your mod a coremod as well.
Played a bit around, got it to work.

The way my implementation would work is:
> Client tries to connect to Server
> Server has updated mods
> Client fetches new mods
> Writes old mod-filenames into a text file
> Client needs to restart
> Upon starting, the coremod checks if the text file exists. If it does, it deletes the old mods before any mod is actually being loaded (Thanks to chickenbones' code to see how it works :P)

Will do a pull-request later :P

**Comment by rheimus** [comment]
This still seems to cause duplicate mod problems even though the mod is just a text file with "D" in it, FML still considers it a mod.
Windows has an issue with deleteOnExit(), something to do with having any reference to the file being active stopping it from working.

**Comment by DPxKnightxZero** [comment]
Running as an admin should fix it for the most part. Since in the Win world its considered a High level command to allow a program to delete things on exit.

**Comment by rheimus** [comment]
Worked around in #31
