### ISSUE TITLE
ServerSync Not Finding Config File

### ISSUE THREAD

**Issue by coryjreid** [superzanti/ServerSync#231]
#### Issue: Not Loading Config File

When creating a custom `serversync-server.json` file next to the serversync.jar file, the config file is never parsed and loaded.

**Comment by rheimus** [comment]
The json config functionality was added in 3.7+

https://github.com/superzanti/ServerSync/releases/tag/v3.7.0-alpha.1

**Comment by rheimus** [comment]
Looks like the wiki does not mention a specific version, I'll update it
