### ISSUE TITLE
Download but don't replace?

### ISSUE THREAD

**Issue by alfuken** [superzanti/ServerSync#239]
Is there a way to configure serversync to download missing files for client, but don't replace them if they have cnahged?
It is often so that config files on client get re-saved with, for example, different timestamps in a config. Example: structurize-client.toml, on serverside it saves with a comment `#structurize.config.optifine.comment` and then client resaves it with `#Optifine Related Settings`. Then on next client launch serversync complains that file differs from the server one and boom, redownload.
Or maybe there's a way to provide `clientconfig`, akin to `clientmods`?..

**Comment by rheimus** [comment]
I usually avoid syncing configs unless it 
is really needed, quite a few configs will have no effect on clients anyway as the server is determining the values present in them.

e.g. client based configs like graphics settings or keybindings really have no place being managed by the server.

**Comment by rheimus** [comment]
This could be added as another type of sync mode though.

**Comment by rheimus** [comment]
You could also put said configs in any folder you like e.g. "my-cool-configs" and use a file redirect to put them in configs

**Comment by alfuken** [comment]
Oh, so that's how redirects work... cool. That thing needs some documenting though. Thanks 👍
