### ISSUE TITLE
Help with serversync-server.json rules

### ISSUE THREAD

**Issue by vico93** [superzanti/ServerSync#246]
#### Issue: 
I'm trying to (re)learn how the new serversync works, previously i was using a GIT repository to sync my modpack, and this .gitignore to filter out all files exclusive to both dedicated server and client. From what i've understand i needed to transfer my ignore list (with minor syntax changes) to `rules\files` section of `serversync-server.json` to filter out the files i didnt want to transfer from server to client AND to keep out in clients if already there. Then i tested setting up a server with all mods, configs and such (FYI Mohist - a Forge/Bukkit hybrid for 1.12) and making a copy of my profile (client) folder and running the server and the client to make a test sync. But the "sync" proved out it only deleted all files on the client except serversync jar/exe, logs and and its config, keeping only empty mod folders and the files at the root of the folder.

#### Logs (serverysync & minecraft)
[Gist with all logs (both client & server AND the rules JSON)](https://gist.github.com/vico93/6cbb631e5589e77a6448af19e90b086f)

**Comment by rheimus** [comment]
I'll look into writing an upgrader for the old format -> new.

It should just be a case of copy pasting the rules you have in `file_ignore_list` into the `files: { ignore: [] }` array, there might be some minor tweaking required to suit the JSON format (quotes and commas).

There is an additional step required currently when setting up a directory, if you want to sync `mods` then you will need this setup:
```

{
  
  "files": {
    "include" ["mods/**"],
    "ignore": []
  }
}
```

**Comment by rheimus** [comment]
Note in the above config the directory entry is telling the client that the `mods` folder is set to be managed by the server and the `mirror` mode means that the directory should _mirror_ the server i.e. remove files that don't exist server-side.

There is also a `push` mode where the server will only send/update files, however, this would very easily leave the client in a state where it can not connect due to conflicting mods so use at your own risk I guess 😁.

**Comment by rheimus** [comment]
If you would like to send client specific mods there are two ways to do so.

#### Recommended
Use the `clientmods` feature:
- create a folder next to `serversync.jar` called `clientmods`
- put the client side only mods in the `clientmods folder`
- set `push_client_mods: true` in `serversync-server.json`

This will put the power in the client's hands to refuse these mod suggestions if they don't want them (e.g. they want to use their own version or a different client mod like a different minimap mod e.t.c.)

#### Not recommended
Use a file redirect to put files from a custom directory into the mods folder.
```
{
  "rules": {
    "files": {
      "include": [
        "my-cool-client-stuff/**"
      ],
      "redirect": [
        {
          "pattern": "my-cool-client-stuff/**",
          "redirectTo": "mods"
        }
      ]
    }
  },
}
```

From the client's perspective, this acts like any other file in the `mods` folder, if they wanted to refuse it they would have to write an ignore pattern that matches it.

**Comment by vico93** [comment]
I do a similar thing of the `clientmods` folder you mentioned. Only difference my client-only folder is called `mods_client` instead. I just sync that and let the client to symlink the folder to `mods\1.12.2` (i also let serversync ignore this path to prefent conflict).

I think my error was not adding the correspondent entry on `files/include` key. Will test now.

**Comment by rheimus** [comment]
Closing this in favor of some docs thrown together here:
https://github.com/superzanti/ServerSync/wiki/Server-setup

**Comment by vico93** [comment]
Sorry. forgot to close this. Seems like i forgot to add the folders on `files/include`. After adding it worked.
