### ISSUE TITLE
[4.0.0]The server does not generate the ‘clientmod’ folder

### ISSUE THREAD

**Issue by EnterFor** [superzanti/ServerSync#248]
#### Serversync Version: 
4.0.0
#### Minecraft Version: 
1.12
#### Issue: 
When I set "push_client_mods": true, the server did not generate the client mods folder.
I can't configure the client Mod.

**Comment by rheimus** [comment]
Workaround is create a folder called `clientmods` manually.

Though it does look like a regression has caused this to not be done automatically.

**Comment by rheimus** [comment]
Clientmods will be created when `push_client_mods` is `true`, look out for this in `4.0.1`
