### ISSUE TITLE
Could not connect to server at ...

### ISSUE THREAD

**Issue by xGenius123** [superzanti/ServerSync#249]
#### Serversync Version: 
4.0.0
#### Minecraft Version: 
1.12.2
#### Issue: 
When i want to synchronize my files with server i get an error "Could not connect to server at  ..."
I don't know if it important but my serversync file is in servers mods folder because i can't use batch files on my server

Logs (serverysync & minecraft)
[Serversync Client log](https://github.com/superzanti/ServerSync/files/6059979/serversync-CLIENT.log)
[Serversync Server log](https://github.com/superzanti/ServerSync/files/6060014/serversync-SERVER.log)
[Minecraft Server log](https://github.com/superzanti/ServerSync/files/6060118/latest.log)

**Comment by rheimus** [comment]
```
[Mar 01, 2021 9:00:46][ServerSync] FINE: Included files: {
  
}
```
Looks like your server config has not included any files, though that should not give you a "cant connect" issue 🤔

**Comment by rheimus** [comment]
I am going to close this as I don't really have enough information to help
