### ISSUE TITLE
Wrapped button

### ISSUE THREAD

**Issue by BloodMan29** [superzanti/ServerSync#25]
Hi,
I have tested your mod but the problem is the wrapped button is not working because custom main menu give me an another button id.
My log:
 [Client thread/INFO] [serversync/]: Your BUTTON_ID is: 6006
ServerSync config:
 # The ID of the button that connects to the server and updates [range: 0 ~ 2147483647, default: 6001]
    I:ButtonID=6001

Thanks in advance !

**Comment by BloodMan29** [comment]
Sorry to have bothered you ! :D
I've just understood the tool..

**Comment by superzanti** [comment]
Not a problem! Glad to hear somebody is using my mod.

**Comment by BloodMan29** [comment]
It's the only mod to do that, I have not found any do that yet.
For now I'm having trouble with the serversync port but it's ok :)
I don't know if you have an irc, that can be useful for me to contact you ?
And thanks for your awesome mod ! :)

**Comment by superzanti** [comment]
The serversync port for 1.8?

I do not currently have an IRC. I may set one up in the future.

**Comment by BloodMan29** [comment]
1.7.10

**Comment by superzanti** [comment]
Ah, this is not a port then. This is the official repo.

**Comment by BloodMan29** [comment]
Ah no the port the number i speak me :D like 25565 or .. etc

**Comment by superzanti** [comment]
OH oh. Sorry, I misunderstood.

Yes, so there are 2 ports, one for serversync that must be forwarded, then the normal minecraft port. These must be different.

**Comment by BloodMan29** [comment]
My hoster have a firewall I think :D So I asked them on what port serversync can connect to.

**Comment by superzanti** [comment]
Good plan. I'm always open for support if you run into trouble.

**Comment by BloodMan29** [comment]
Also I know i'm not in the good issue, but how the mod work with client-side mods ? I'm sorry if the question is duplicate x time but you should write more information on curse or here on github about it !

**Comment by superzanti** [comment]
Sorry, life has been pretty busy so I haven't been able to do much with this mod recently. ATM i don't have a house, but in august I will so hopefully things will free up around then.


Currently client-side mods are not updated. Only mods that are on both server and client side are updated and synced. However, if you wish for your clients to have client-side only mods, just add them to the ignore list.

**Comment by BloodMan29** [comment]
Oh okay, don't speed up things to help nub like me :D Take your time to be good at your side and/or do what do you want to do :)
