### ISSUE TITLE
File serversync-4.0.0.jar is for an older version of Forge and cannot be loaded

### ISSUE THREAD

**Issue by trungtrg** [superzanti/ServerSync#250]
Hello,

I got this error while running modpack Engimatica 6 - Forge 36.0.40 - Minecraft ver 16.5. I put the jar file in the mods folder instead of running batch script or commandline since my hosting company does not allow start up parameter or additional jar file to run. Is there anyway to go around this?

Thank you!

**Comment by rheimus** [comment]
Serversync no longer supports being loaded on its own by forge.

There is a project for loading it via forge here https://github.com/rheimus/serversync-forge-loader, I can not make any guarantee about your server host being happy about it though.

It loads serversync in the process spawned by forge so it is essentially the same as any other mod.
