### ISSUE TITLE
Slow speeds when syncing nonlocally

### ISSUE THREAD

**Issue by MrKashew** [superzanti/ServerSync#257]
#### Issue: 

Nothing unusual in logs. Seems to hang on even 5mb mods, modpack is ~300mb total and takes incredibly long to sync (hours). Are there jvm arguments to optimize server speed?
Biggest clue could potentially be that it seems that sync is fast when tested via computer connected to same internet as server, but not when connected on a different internet (tried 3 different clients, all with fast internet speeds). Upload speed of server isn't too great (5 Mbps) but shouldn't be taking hours for 300mb modpack. Any insight?

**Comment by rheimus** [comment]
It's possible that the buffer sizes on either end of the socket are causing slow transfers (8mb by default).

I don't really have enough information to help, have you tried using other transfer tools to see if serversync is the issue or just the network itself?

**Comment by rheimus** [comment]
Hmm, seems like file transfer client side of the socket is limited to 1024 bytes. I'll have a dig around into what is limiting there.

**Comment by rheimus** [comment]
@MrKashew Have a try using the artifacts from this job
https://github.com/superzanti/ServerSync/actions/runs/660579400 (package)

I have changed from writing through Object*Stream's when transferring files as it seems to be hard locked to 1024 bytes at a time.

**Comment by MrKashew** [comment]
Working far faster in my test, no longer hanging on larger mods for me!

**Comment by rheimus** [comment]
Released this fix in `4.1.0`, closing as resolved.
