### ISSUE TITLE
Server ignore patterns do not prevent client from deleting mods in Client mod folder

### ISSUE THREAD

**Issue by TylzSomeone** [superzanti/ServerSync#261]
#### Issue: Ignore patterns do not affect client

This is more of a question. I setup an ignore list on the server side for mods such as journeymap. I do not want journeymap in the server mods but I want clients to be able to use the mod and not have the mod deleted when they run sync. They can setup their own .cfg and ignore list, but is this not something I can do on the server side so my players don't have to worry about it?

**Comment by TylzSomeone** [comment]
Maybe this is part of the refuse client mods config?

**Comment by TylzSomeone** [comment]
Or are there other modes aside from mirror that can be used?

**Comment by TylzSomeone** [comment]
Or is there a good way to sync "serversync-client.json" to their pc with the ignore patterns added?

**Comment by HaibaraGT** [comment]
Look is [https://github.com/superzanti/ServerSync/wiki/Client-Mods](url)
This project can meet your needs！！

**Comment by HaibaraGT** [comment]
> Or is there a good way to sync "serversync-client.json" to their pc with the ignore patterns added?

Look is https://github.com/superzanti/ServerSync/wiki/Client-Mods
This project can meet your needs！！

**Comment by TylzSomeone** [comment]
You are the best thank you again for solving my problems!!!!

**Comment by TylzSomeone** [comment]
With refuse client mods selected, the sync action still downloads all the mods in the clientmods folder.

**Comment by rheimus** [comment]
#165 Is tracking allowing servers to send a list of known client mods that they don't want serversync to delete.

For now the only real option is using `clientmods`, you could set your mods directory to `push` mode but that would very easily leave your clients in a position where they cant connect due to invalid or incompatible mods being present.

**Comment by TylzSomeone** [comment]
I am using the clientmods, a client is trying to refuse the push of the clientmods but it is not allowing it. It still forces the mods to be downloaded

**Comment by rheimus** [comment]
Adding an ignore pattern on the client that matches the file that they don't want will probably work as an alternative to `refuse_client_mods`.

The refuse functionality probably broke when I changed to file redirects instead of custom handling for clientmods.

**Comment by Zuosizhu** [comment]
Actually, ignoring means it's like it doesn't there. So if you set it to mirror mode, client will delete it because "it's not there".

**Comment by rheimus** [comment]
> Actually, ignoring means it's like it doesn't there. So if you set it to mirror mode, client will delete it because "it's not there on the server".

If the server configures a file to be ignored it will behave as it that file does not exist on the server yes.

If the client configures a file to be ignored it will (should) prevent the file from being accepted and prevent the said file from being deleted as well.

**Comment by Zuosizhu** [comment]
> If the client configures a file to be ignored it will (should) prevent the file from being accepted and prevent the said file from being deleted as well.

Yes, it does. Sometimes the server don't have so much bandwidth. And large mods are required to be downloaded somewhere else to prevent lags(and it seems this syncing doesn't support large mods as well ).

**Comment by rheimus** [comment]
If you are looking to limit bandwidth you could always reduce the buffer size.
```
"connection": {
    "port": 38067,
    "buffer": 1048576 <---
},
```

**Comment by rheimus** [comment]
Fixed client ignore not working, for any other issues raised in this ticket please raise a different ticket if they are still a problem
https://github.com/superzanti/ServerSync/releases/tag/v4.2.0
