### ISSUE TITLE
[Need Help] Error at start

### ISSUE THREAD

**Issue by Matthysse** [superzanti/ServerSync#263]
Hello!

I have this error when starting my server, and I don't understand, I did put a valid port in the .json,, I use the forge mod to start it because the server is hosted. I don't understand what's wrong

https://pastebin.com/h6EUtrLT

**Comment by rheimus** [comment]
Apologies, seems that I missed a notification for this.

Looks somewhat related to #266 might need to set the locale to something with two parts (en_uk) (en_us) etc

**Comment by rheimus** [comment]
Closing for now, feel free to open another issue if this persists beyond the workaround in #266
