### ISSUE TITLE
Slow startup time

### ISSUE THREAD

**Issue by Creepercdn** [superzanti/ServerSync#265]
#### Serversync Version: 
v4.0+

ServerSync's GUI is too slow.

**Comment by rheimus** [comment]
The title would indicate the initial startup time but are you specifically referring to the startup or other parts of the GUI being slow.

**Comment by Zuosizhu** [comment]
It's slow at startup, with an average delay of over 40 seconds. My computer is I7 8700k with double 8G drams, Samsung PM981 SSD(OEM version of 970 evo plus)

**Comment by rheimus** [comment]
Could be related to CSS loading, I'll investigate whether the assets have been optimized.
