### ISSUE TITLE
Client still receive clientmods when refused

### ISSUE THREAD

**Issue by Zuosizhu** [superzanti/ServerSync#267]
#### Serversync Version: 
4.1.0
#### Minecraft Version: 
irrelevant
#### Issue: 
If the client refuse to receive clientmods, it still receives

**Comment by rheimus** [comment]
#262 most likely fixed this.

**Comment by rheimus** [comment]
Should be fixed in 4.2.0 https://github.com/superzanti/ServerSync/releases/tag/v4.2.0
