### ISSUE TITLE
Uploaded new mods, but client server sync not getting new mods

### ISSUE THREAD

**Issue by IconFive** [superzanti/ServerSync#271]
#### Issue: New mods uploaded on the server, I use forge, have server sync forger loader in mods folder, server syc 4.1.0 in root folder of server, restarted the server. But when client click sync, it's not retrieving new mods.

<details>
<summary>Logs (serverysync & minecraft)</summary>
<pre>

Jun 04, 2021 4:47:48 PM com.superzanti.serversync.util.LoggerInstance log
INFO: Root dir: C:\Users\xiany\Desktop\Forge Server
Jun 04, 2021 4:47:48 PM com.superzanti.serversync.util.LoggerInstance log
INFO: Running version: v4.1.0
Jun 04, 2021 4:47:48 PM com.superzanti.serversync.util.LoggerInstance log
INFO: Loading language file: en_US
Jun 04, 2021 4:47:48 PM com.superzanti.serversync.util.LoggerInstance log
INFO: Starting server in mode: 2
Jun 04, 2021 4:47:48 PM com.superzanti.serversync.util.LoggerInstance log
INFO: Starting scan for managed files: Jun 4, 2021
Jun 04, 2021 4:47:48 PM com.superzanti.serversync.util.LoggerInstance log
INFO: Ignore patterns: {
  **/serversync-*.jar
  **/serversync-*.cfg
}
Jun 04, 2021 4:47:49 PM com.superzanti.serversync.util.LoggerInstance debug
FINE: Included files: {
  mods\adaptive_performance_tweaks_1.16.5-1.0.5.jar, Pattern: mods/**
  mods\AppleSkin-mc1.16.2-forge-1.0.14.jar, Pattern: mods/**
  mods\ars_nouveau-1.16.5-1.18.jar, Pattern: mods/**
  mods\Artifacts-Mod-1.16.5.jar, Pattern: mods/**
  mods\astikorcarts-1.16.5-1.1.1.jar, Pattern: mods/**
  mods\betterweather-1.2.9.jar, Pattern: mods/**
  mods\BiomesOPlenty-1.16.5-13.1.0.469-universal.jar, Pattern: mods/**
  mods\Blood-Magic-Mod-1.16.5.jar, Pattern: mods/**
  mods\catalogue-1.2.1-1.16.5.jar, Pattern: mods/**
  mods\CookingForBlockheads_1.16.5-9.3.2.jar, Pattern: mods/**
  mods\CosmeticArmorReworked-1.16.5-v2.jar, Pattern: mods/**
  mods\create-mc1.16.5_v0.3.1c.jar, Pattern: mods/**
  mods\Cucumber-1.16.4-4.1.9.jar, Pattern: mods/**
  mods\culinaryconstruct-forge-1.16.5-4.0.0.6.jar, Pattern: mods/**
  mods\curios-forge-1.16.5-4.0.5.1.jar, Pattern: mods/**
  mods\decorative_blocks-1.16.4-1.7.2.jar, Pattern: mods/**
  mods\dungeons_plus-1.16.5-1.1.5.jar, Pattern: mods/**
  mods\dwmh-1.16.4-0.4.0.2.jar, Pattern: mods/**
  mods\expandability-2.0.1-forge.jar, Pattern: mods/**
  mods\ferritecore-2.0.4-forge.jar, Pattern: mods/**
  mods\foodexpansion-1.6.1.jar, Pattern: mods/**
  mods\geckolib-forge-1.16.5-3.0.36.jar, Pattern: mods/**
  mods\gravestone-1.16.5-1.0.4.jar, Pattern: mods/**
  mods\Guide-API-VP-1.16.4-2.2.1.jar, Pattern: mods/**
  mods\ImmersiveEngineering-1.16.5-5.0.0-135.jar, Pattern: mods/**
  mods\ironchest-1.16.4-11.2.10.jar, Pattern: mods/**
  mods\jei-1.16.5-7.7.0.101.jar, Pattern: mods/**
  mods\logprot-1.16-1.3.jar, Pattern: mods/**
  mods\Mantle-1.16.5-1.6.103.jar, Pattern: mods/**
  mods\mcw-bridges-1.0.5-mc1.16.5-4.jar, Pattern: mods/**
  mods\mcw-doors-1.0.2-mc1.16.5.jar, Pattern: mods/**
  mods\mcw-furniture-2.0.1-mc1.16.5.jar, Pattern: mods/**
  mods\mcw-windows-1.0.3-mc1.16.5.jar, Pattern: mods/**
  mods\minecolonies-1_16_5.jar, Pattern: mods/**
  mods\minecraft2discord-forge-1.16.x-3.0.13.jar, Pattern: mods/**
  mods\mobcatcher-3.2.jar, Pattern: mods/**
  mods\Morpheus-1.16.5-4.2.70.jar, Pattern: mods/**
  mods\MysticalAgradditions-1.16.4-4.1.5.jar, Pattern: mods/**
  mods\MysticalAgriculture-1.16.4-4.1.8.jar, Pattern: mods/**
  mods\MysticalCustomization-1.16.4-2.1.4.jar, Pattern: mods/**
  mods\obfuscate-0.6.1-1.16.3.jar, Pattern: mods/**
  mods\OreExcavation-1.8.157.jar, Pattern: mods/**
  mods\packedup-1.0.22-mc1.16.4.jar, Pattern: mods/**
  mods\pamhc2crops-1.16.3-1.0.2.jar, Pattern: mods/**
  mods\pamhc2foodcore-1.16.3-1.0.2.jar, Pattern: mods/**
  mods\pamhc2foodextended-1.16.3-1.0.2.jar, Pattern: mods/**
  mods\pamhc2trees-1.16.3-1.0.1.jar, Pattern: mods/**
  mods\Patchouli-1.16.4-51.jar, Pattern: mods/**
  mods\randompatches-2.4.4-forge.jar, Pattern: mods/**
  mods\reliquary-1.16.5-1.3.5.1098.jar, Pattern: mods/**
  mods\silent-lib-1.16.3-4.9.6.jar, Pattern: mods/**
  mods\simpleplanes-1.16.5-4.4.1.jar, Pattern: mods/**
  mods\smallships-1.16.5-1.8.5.jar, Pattern: mods/**
  mods\smoothboot-forge-1.16.4-1.2.2.jar, Pattern: mods/**
  mods\spark-forge.jar, Pattern: mods/**
  mods\structure_gel-1.16.5-1.7.7.jar, Pattern: mods/**
  mods\structurize-0.13.113-ALPHA-universal.jar, Pattern: mods/**
  mods\TelePastries-1.16.5-0.3.7.jar, Pattern: mods/**
  mods\thutcore-1.16.4-8.2.0.jar, Pattern: mods/**
  mods\thutessentials-1.16.4-4.1.4.jar, Pattern: mods/**
  mods\thutperms-1.16.4-4.0.0.jar, Pattern: mods/**
  mods\thuttech-1.16.4-9.1.2.jar, Pattern: mods/**
  mods\Tinkers-Construct-Mod-1.16.5.jar, Pattern: mods/**
  mods\towers_of_the_wild-1.16.4-2.0.1.jar, Pattern: mods/**
  mods\TrackAPI-1.16.4-forge-1.2.1.jar, Pattern: mods/**
  mods\treasure-bags-1.16.3-1.4.0.jar, Pattern: mods/**
  mods\twilightforest-1.16.5-4.0.490-universal.jar, Pattern: mods/**
  mods\valhelsia_core-16.0.8.jar, Pattern: mods/**
  mods\valhelsia_structures-1.16.5-0.1.1.jar, Pattern: mods/**
  mods\Vampirism-1.16.4-1.7.11.jar, Pattern: mods/**
  mods\vehicle-mod-0.45.2-1.16.3.jar, Pattern: mods/**
  mods\w2w-1.16.1-0.0.5.2.jar, Pattern: mods/**
  mods\walljump-forge-1.16.4-1.3.7.jar, Pattern: mods/**
  mods\Waystones_1.16.5-7.5.1.jar, Pattern: mods/**
  mods\Xaeros_Minimap_21.9.0.1_Forge_1.16.5.jar, Pattern: mods/**
}
Jun 04, 2021 4:47:49 PM com.superzanti.serversync.util.LoggerInstance debug
FINE: Ignored files: {
  mods\serversync-forge-loader-2.0.1.jar, Pattern: **/serversync-*.jar
}
Jun 04, 2021 4:47:50 PM com.superzanti.serversync.util.LoggerInstance log
INFO: Manifest files: {
  FileEntry{path='mods\adaptive_performance_tweaks_1.16.5-1.0.5.jar', hash='ca3400c6a58842f1f4220c3de198c3d8832463d5c2279a630d4ba2ba5294e1a3', redirectTo=''}
  FileEntry{path='mods\AppleSkin-mc1.16.2-forge-1.0.14.jar', hash='e0d39f6b138e853d6171bd51fa158545d68cab5e718a01feb919d37964e5eb4f', redirectTo=''}
  FileEntry{path='mods\ars_nouveau-1.16.5-1.18.jar', hash='1d3d03f0cbea8081b34dd19469040f5771b2c9cd2c86a15c38f6d3b523d1ad4c', redirectTo=''}
  FileEntry{path='mods\Artifacts-Mod-1.16.5.jar', hash='ec0e4c115a63cc35a91663cdea7551ca55a43cc15870d6aaace42e02bd412c8d', redirectTo=''}
  FileEntry{path='mods\astikorcarts-1.16.5-1.1.1.jar', hash='c8f45f2934929db7b76281e1b50b2a09d1b6b8fa480600dfeb113ce8f604ad16', redirectTo=''}
  FileEntry{path='mods\betterweather-1.2.9.jar', hash='0442c040001f2f0831b6466846beaf314b748ca7241b743c823ea49a4dc973e9', redirectTo=''}
  FileEntry{path='mods\BiomesOPlenty-1.16.5-13.1.0.469-universal.jar', hash='de3c9813bf3c7d3ff6e7d40a8cf091a03b53291f2f30b8a6feab9302d7482644', redirectTo=''}
  FileEntry{path='mods\Blood-Magic-Mod-1.16.5.jar', hash='ae2ed94cb91df787698c27420ebe7a00881a2395c952776f12d4b37adf8db9de', redirectTo=''}
  FileEntry{path='mods\catalogue-1.2.1-1.16.5.jar', hash='d3832f295a404b3488cbb8b4f71b605b9d8954cc956b46665ddd6494aaf65196', redirectTo=''}
  FileEntry{path='mods\CookingForBlockheads_1.16.5-9.3.2.jar', hash='55bf88b1f7e5b23812999340a89b05e210edff05fa2550c2c1c6c7733dc4f157', redirectTo=''}
  FileEntry{path='mods\CosmeticArmorReworked-1.16.5-v2.jar', hash='fa06d8229afd49d88fffeb92ebdf712c0fa1e87bb59862e9ae456cb86e94f4ad', redirectTo=''}
  FileEntry{path='mods\create-mc1.16.5_v0.3.1c.jar', hash='af38879c829da1462e5de9c6ffc1b0488c3efbd50d81c1e72efc98973edf8c4c', redirectTo=''}
  FileEntry{path='mods\Cucumber-1.16.4-4.1.9.jar', hash='8685c263087fa8cb6496a20810053219627c620c0335d0a81ec24be9b56dd058', redirectTo=''}
  FileEntry{path='mods\culinaryconstruct-forge-1.16.5-4.0.0.6.jar', hash='333e27a8c3dcb719a5ceadeeaf1ba5154e1ba0792c44788d08ec419916f89bac', redirectTo=''}
  FileEntry{path='mods\curios-forge-1.16.5-4.0.5.1.jar', hash='1e01e467c3b8d379926b5dc8d40d8088092dc7928c0bb25a49d545de82ff32a8', redirectTo=''}
  FileEntry{path='mods\decorative_blocks-1.16.4-1.7.2.jar', hash='f12dbfe76e36cdec65b8a575fc671f0291323a0de5ff420ff196d16bd19e6f84', redirectTo=''}
  FileEntry{path='mods\dungeons_plus-1.16.5-1.1.5.jar', hash='2dfad14a95f15d3a1b0128b5b1bae1f0ceda491311812c25955abc7633247be1', redirectTo=''}
  FileEntry{path='mods\dwmh-1.16.4-0.4.0.2.jar', hash='177c86c46058119dc0cb43ae83d70e3290ad1a9801c43f79fc60393d12680c5a', redirectTo=''}
  FileEntry{path='mods\expandability-2.0.1-forge.jar', hash='0959cffb3a545730e6b2e1377bb89b59ff96e7f9142f54cc8035ab4fa2fc76e1', redirectTo=''}
  FileEntry{path='mods\ferritecore-2.0.4-forge.jar', hash='732475e4f507725334a47acef9f38a5588066073c7082b23c02e8b39638d942c', redirectTo=''}
  FileEntry{path='mods\foodexpansion-1.6.1.jar', hash='805b43f02ecadbd8af054ba744d0851a50bbe0869241e46568b6901752e90fa7', redirectTo=''}
  FileEntry{path='mods\geckolib-forge-1.16.5-3.0.36.jar', hash='9fa818f44f5122ac63f39dfd322d024e88151f63d815a4b23767f5a7caa751eb', redirectTo=''}
  FileEntry{path='mods\gravestone-1.16.5-1.0.4.jar', hash='b82f7a67aab377cf9fe3cbffab168d5aeda241f2e7c56c32d24cce72618806ff', redirectTo=''}
  FileEntry{path='mods\Guide-API-VP-1.16.4-2.2.1.jar', hash='48f796581b4dc6c21fa25289bbed84a3c33a7c2d783b4cf1ac668dcb3b551058', redirectTo=''}
  FileEntry{path='mods\ImmersiveEngineering-1.16.5-5.0.0-135.jar', hash='8bb77a18ddd55edb89157adce59d4d8f57ad38720e050c32bae4858bcc8d2051', redirectTo=''}
  FileEntry{path='mods\ironchest-1.16.4-11.2.10.jar', hash='5208572a3f07647ca3cfed9f7414957acd0059b7f708d2518f4c73c98beae6be', redirectTo=''}
  FileEntry{path='mods\jei-1.16.5-7.7.0.101.jar', hash='0f527f3ea2e0a28b5c0b72d06c688f0db1058aa12b6173be747fc5b672945fb4', redirectTo=''}
  FileEntry{path='mods\logprot-1.16-1.3.jar', hash='65eb68469a3d517d8707a1235f1c26c01758f456d1cda014ebb7740333f330ab', redirectTo=''}
  FileEntry{path='mods\Mantle-1.16.5-1.6.103.jar', hash='713dce2d43d181243c0210ec9ebc0877d9f883c82e23fabff5f2981c69610a8e', redirectTo=''}
  FileEntry{path='mods\mcw-bridges-1.0.5-mc1.16.5-4.jar', hash='eb4fc6f204486508a182d4d5430d84ed0f4652ad712a970b0d55a18d2e913de0', redirectTo=''}
  FileEntry{path='mods\mcw-doors-1.0.2-mc1.16.5.jar', hash='cea684ad9bf1fa75ba2685b3e521b2e1806f428681f7d929e3f937b161fb397e', redirectTo=''}
  FileEntry{path='mods\mcw-furniture-2.0.1-mc1.16.5.jar', hash='7f81b95c128ce97f3c41e29a4e98618c591f96321b53b718b5c3b6b8d3cb619e', redirectTo=''}
  FileEntry{path='mods\mcw-windows-1.0.3-mc1.16.5.jar', hash='4768c9a135a37f8eba0d10600d01d5d8cf563c38c0c95f00c431bfe8a63c4123', redirectTo=''}
  FileEntry{path='mods\minecolonies-1_16_5.jar', hash='4b9f5340feaef19523d7ee4edaa77ed3aa13c0ea1e4aa7087ea3534e2bf701cf', redirectTo=''}
  FileEntry{path='mods\minecraft2discord-forge-1.16.x-3.0.13.jar', hash='b59d16b286a92ec1f56aa0c8285f1ab1d5555226c0184bb926c305d70961db83', redirectTo=''}
  FileEntry{path='mods\mobcatcher-3.2.jar', hash='d0527136e3e9acb769e38008fecbcf105e753fc0ee152300fa3f43e672c259c4', redirectTo=''}
  FileEntry{path='mods\Morpheus-1.16.5-4.2.70.jar', hash='2852376ecc7ea4856b4d8b26d0144c90426106e03f2372cfa01007342235076d', redirectTo=''}
  FileEntry{path='mods\MysticalAgradditions-1.16.4-4.1.5.jar', hash='96d1254fd23dbbf5b14e5e54f9a0754767a226ac5e61b3278817fb4cca21401e', redirectTo=''}
  FileEntry{path='mods\MysticalAgriculture-1.16.4-4.1.8.jar', hash='ee1b32c21c4c856aa9b49e84e0f5ac70a3dcbe739a032b654218fc5e417c3cf2', redirectTo=''}
  FileEntry{path='mods\MysticalCustomization-1.16.4-2.1.4.jar', hash='709559369ce6bfe89299f69c2a3e428c56ae57293a959606f9f5aaa6fd1b9d8e', redirectTo=''}
  FileEntry{path='mods\obfuscate-0.6.1-1.16.3.jar', hash='a61c113efc4149ee852ca276e8bf8ea524018f43c427ff19835b6ae517aecd6c', redirectTo=''}
  FileEntry{path='mods\OreExcavation-1.8.157.jar', hash='3cc810e0cd36b507915f3fe69b69b7eeb666ebd791473dc99bbc47e6af737990', redirectTo=''}
  FileEntry{path='mods\packedup-1.0.22-mc1.16.4.jar', hash='3ed08b922f25a1898686cfbb732979be8acadaceab9c65c01ff343d0bc003696', redirectTo=''}
  FileEntry{path='mods\pamhc2crops-1.16.3-1.0.2.jar', hash='5ebb51293d3e56ccf93875b7a4943577d78c1ee79401115230bb28cebbc7e832', redirectTo=''}
  FileEntry{path='mods\pamhc2foodcore-1.16.3-1.0.2.jar', hash='e4414d35013e746e5b06256a08dd957a814b17cebcb035899a84a3692d08b544', redirectTo=''}
  FileEntry{path='mods\pamhc2foodextended-1.16.3-1.0.2.jar', hash='886ec5e6dca66382b99765b0033d17e270b792171a75dd8eb41fcfd86a5641e9', redirectTo=''}
  FileEntry{path='mods\pamhc2trees-1.16.3-1.0.1.jar', hash='e0f38f6a61e1da87981a249d520f2a8e43c4cefd29693076caf74ab8c5fe697f', redirectTo=''}
  FileEntry{path='mods\Patchouli-1.16.4-51.jar', hash='eb63743b3926dbaea295f50959cab4df8c6e642bdb40090640e6bcfbc6b62566', redirectTo=''}
  FileEntry{path='mods\randompatches-2.4.4-forge.jar', hash='5d63e2bdf2648a1d1b9ffe741479185359de783952a111444187483156d6d602', redirectTo=''}
  FileEntry{path='mods\reliquary-1.16.5-1.3.5.1098.jar', hash='1ffb5cb74522c451bef1328e46ed8570636a92ee0e58422a1cc15cffce2cf83b', redirectTo=''}
  FileEntry{path='mods\silent-lib-1.16.3-4.9.6.jar', hash='ccd8757d3a8b5447bb4192c1966099cd3671b2f7e49fb0d889f32359ad2d2d45', redirectTo=''}
  FileEntry{path='mods\simpleplanes-1.16.5-4.4.1.jar', hash='368e59241f6a73b3d12257c0d776c1a75c9a9ffa043a72fc39f0a8dcbb26ced1', redirectTo=''}
  FileEntry{path='mods\smallships-1.16.5-1.8.5.jar', hash='807ff3c2fbe842c9941a4b0080c36e50cb885cc15d75bb1f0077f0ce72157a2b', redirectTo=''}
  FileEntry{path='mods\smoothboot-forge-1.16.4-1.2.2.jar', hash='067e469f30692cb51dc21f593eb0be8664fd694eb3acc2f6f12ca161100186aa', redirectTo=''}
  FileEntry{path='mods\spark-forge.jar', hash='f4148cb08a222d61454237b68e19d5a853621535ca2134c0948b83c543a0b5db', redirectTo=''}
  FileEntry{path='mods\structure_gel-1.16.5-1.7.7.jar', hash='84c2edd3a9e6cdbe9c7ee76989b7c8465bd75bab117d68516461a98df136e42f', redirectTo=''}
  FileEntry{path='mods\structurize-0.13.113-ALPHA-universal.jar', hash='48e81d2c1ee5c69fe71bfacc95986468dc088634ba98c8b789d0cc18b406d7c5', redirectTo=''}
  FileEntry{path='mods\TelePastries-1.16.5-0.3.7.jar', hash='7ed1e30eb063eca4358822de58b506aa28f10f244097e241237af1bebcb5bb38', redirectTo=''}
  FileEntry{path='mods\thutcore-1.16.4-8.2.0.jar', hash='add4da8f21bfb3366533f94baf17096aff9ca4aefc17563833f3af3152cfbfcc', redirectTo=''}
  FileEntry{path='mods\thutessentials-1.16.4-4.1.4.jar', hash='6c3b7e3051065ee426e06b545d3416bc6cccab550b8852e20d02acbb9d4b14a9', redirectTo=''}
  FileEntry{path='mods\thutperms-1.16.4-4.0.0.jar', hash='0e165a288c44b03d3cde2e44a46ae8c336618831def2e9a797e340f48c02e39d', redirectTo=''}
  FileEntry{path='mods\thuttech-1.16.4-9.1.2.jar', hash='6496431f0751bfb452873ce906c3362b1a603478a67e57bafddad7882c6cad10', redirectTo=''}
  FileEntry{path='mods\Tinkers-Construct-Mod-1.16.5.jar', hash='d1370977eea5ed23ce4199b62c8087afa63d8a22b0ccf1315cb8ed43642b49aa', redirectTo=''}
  FileEntry{path='mods\towers_of_the_wild-1.16.4-2.0.1.jar', hash='fcd0e3f808569f0e547313a1ea3563c9a5d2fa8fbb638678eed6e46c1d8cfaf1', redirectTo=''}
  FileEntry{path='mods\TrackAPI-1.16.4-forge-1.2.1.jar', hash='456571aef58f014286807dd77399425a314d976fb2600a2601141e5fdfa03624', redirectTo=''}
  FileEntry{path='mods\treasure-bags-1.16.3-1.4.0.jar', hash='30b47076306bbeb24f84d644a9ac0b5cf363d176f54784e13c786870a22da004', redirectTo=''}
  FileEntry{path='mods\twilightforest-1.16.5-4.0.490-universal.jar', hash='2dd772fa68cbe1d63abd43f75c0fbe9478220504d801686d980b9d5e89300358', redirectTo=''}
  FileEntry{path='mods\valhelsia_core-16.0.8.jar', hash='1a1eec157e5b3952f0c01815b74e49a681277e2dbd1e449e7490aaf4e0191db9', redirectTo=''}
  FileEntry{path='mods\valhelsia_structures-1.16.5-0.1.1.jar', hash='5e6a7ca406f3dafe690c50b59913d15556c8f75630b0e8cedb26e8f31b71d465', redirectTo=''}
  FileEntry{path='mods\Vampirism-1.16.4-1.7.11.jar', hash='4527e845a620d7835204547516401b0eceac2778e9e9cf315d51dba19666b386', redirectTo=''}
  FileEntry{path='mods\vehicle-mod-0.45.2-1.16.3.jar', hash='6998fbdab9cda80d176647286c9edd7a52ae80b00336bae0530340b5eeb82d95', redirectTo=''}
  FileEntry{path='mods\w2w-1.16.1-0.0.5.2.jar', hash='17aadfa596779c05c79611ed70ebc253d5ede0c8e009ab243c03f1f92f76f0b5', redirectTo=''}
  FileEntry{path='mods\walljump-forge-1.16.4-1.3.7.jar', hash='14da39fd203ce2d1a2580a49db068442fd527bc5deb0405eab7e996143a0ee54', redirectTo=''}
  FileEntry{path='mods\Waystones_1.16.5-7.5.1.jar', hash='19fecbc1610e441f4d50f2c698ab88a4104d8c6c28f0d651f7fb15f24e359213', redirectTo=''}
  FileEntry{path='mods\Xaeros_Minimap_21.9.0.1_Forge_1.16.5.jar', hash='c7c7cf1ecd5c270c0536ae40322a9c07096f37de99d433086133b6a0e8f5cf15', redirectTo=''}
}
Jun 04, 2021 4:47:50 PM com.superzanti.serversync.util.LoggerInstance debug
FINE: Creating new server socket
Jun 04, 2021 4:47:50 PM com.superzanti.serversync.util.LoggerInstance error
SEVERE: Socket already bound at: 38067

</pre>
</details>

**Comment by rheimus** [comment]
```
SEVERE: Socket already bound at: 38067
```

Something is already running on the port that you have configured for SS, this might indicate that SS is not being shut down correctly when started from forge.

**Comment by IconFive** [comment]
Oh okay I will try this out

**Comment by rheimus** [comment]
That should be fine, it might be that the companion forge loader mod needs to listen for server shutdown events and kill the process.

Though I would have expected the process to be tied to forge and exit when it does.

**Comment by IconFive** [comment]
So when I close server via stop command it stops and save everything, I looked at my process lists and saw that there is still one java instance still running, I had to manually close it. I restarted the server up and tried syncing my client, and it works, it started getting the new mods. 

So for some reason, when stopping the server, it doesn't close out the listening port and causing this issue.

**Comment by rheimus** [comment]
That most likely confirms that the forge loader needs to manually shut down SS on a server close event. I'll raise an issue with that project.
