### ISSUE TITLE
Path not platform agnostic

### ISSUE THREAD

**Issue by Nekotato1412** [superzanti/ServerSync#282]
#### Issue: Path is not platform agnostic

There is an issue with how serversync actually handles the path, it doesn't seem to be platform agnostic. Due to the differences in Linux and Windows paths it interprets the path as a filename and as a result doesn't actually put the files in the correct directory.

Linux uses Forward slashes(/) and Windows uses Backslashes(\\)

It is suggested to use some sort of path helper that fixes these issues.

**Comment by rheimus** [comment]
Windows is in general quite happy to use forward or backward slashes 🤷‍♂️.

I'm reopening this to track doing some testing and releasing the fix for this.
