### ISSUE TITLE
Cannot find /config/serversync/, is it automatically generated?

### ISSUE THREAD

**Issue by Serial-Comma** [superzanti/ServerSync#283]
#### Serversync Version: 
4.2.0
#### Minecraft Version: 
1.16.5
#### Issue: 
I want to configure client mods for serversync, but am unable to because /config/serversync/serversync-server.cfg doesnt exist (the whole serversync folder doesn't exist)
<details>
I run serversync on a linux distribution with no desktop environment so I can't use the GUI (MineOS). I installed MineOS using the Non-standard usage (forge 1.14 +) and so far it works perfectly for syncing mods. However, I wanted to configure clientmods, but even after multiple restarts there is no serversync folder in /config/. Therefore, I wish to ask whether this folder is supposed to be automatically generated or whether it is supposed to be user generated. If it is user generated, is there a copy of the default .cfg file that I'm supposed to put in there?

<pre>

</pre>
</details>

**Comment by HaibaraGT** [comment]
The configuration file of version 4.0 is in the root directory, which is at the same level as Serversync.jar.

**Comment by rheimus** [comment]
The config is auto generated if no previous type is found, if an old style config is found then it will try to convert that to the 4.0 version.
