### ISSUE TITLE
Issues ignoring a symlink to a included folder

### ISSUE THREAD

**Issue by vico93** [superzanti/ServerSync#284]
#### Issue: 
Hello! I'm trying to sync my profile (modpack) through ServerSync. To prevent client-only mods to be mixed with "dual-side" mods i put the client mods in a folder called `mods_client` and symlink the folder with `mods\1.12.2` to be loaded with Forge.
The question is, while i want to send the `mods_client` content to the client, i don't want to send the symlinked folder (`mods\1.12.2` - the user will make the symlink himself after the sync ).
So i configured my server and tested the sync, and although i was able to not allow the symlink to be replicated to it only creates an empty `mods_client` folder. For me seems like serversync is actually resolving the symlink and applying the files ignore directive to the original folder.

Below in the gist is the server config and the client log to try to elucidate the problem.
https://gist.github.com/vico93/034504a7cd9d41c67a889d17bd5eeff2

**Comment by rheimus** [comment]
Documentation is a bit out of date but have you tried the clientmods feature of serversync?
https://github.com/superzanti/ServerSync/wiki/Client-Mods

I have not really put any systems in place around supporting symlinks so I assume it is just using Java defaults for symlink resolving.

**Comment by vico93** [comment]
I will take that on mind. Thanks a lot!
