### ISSUE TITLE
What java version does serversync use?

### ISSUE THREAD

**Issue by Serial-Comma** [superzanti/ServerSync#285]
#### Serversync Version: 
4.2.0
#### Minecraft Version: 
1.16.5
#### Issue: 
My friend on macOS is unable to launch serversync by double clicking. 

<details>
He has [Temurin 16](https://adoptium.net/releases.html) installed but double clicking it yields nothing. He used serversync-4.2.0.jar white it was in his .minecraft folder.

Troubleshooting says nothing because macOS can't use jarFix.

How do I solve this? 

Thank you
<pre>
</pre>
</details>

**Comment by rheimus** [comment]
It should work on anything down to 8 ish area, they probably don't have a java distribution that includes JavaFX.

I have not got particularly far with packaging JavaFX into the app.

**Comment by Serial-Comma** [comment]
Any way I can get serversync to work on macOS then?

**Comment by rheimus** [comment]
`serversync -o` at the moment does not use any GUI, so it would not need JavaFX.

Alternatively the person in question could install a java distribution that already includes FX with it, I am probably going to bin FX in favor of going back to swing but that will take quite some time.

**Comment by Serial-Comma** [comment]
I see. Not too familiar with Java, what does 'using a distribution with FX' mean?

**Comment by rheimus** [comment]
https://www.azul.com/downloads/?os=macos&package=jre-fx

Zulu for an example has distribution options that include JavaFX.

**Comment by Serial-Comma** [comment]
Understood
