### ISSUE TITLE
[4.2.0]The configuration file cannot be synchronized

### ISSUE THREAD

**Issue by EnterFor** [superzanti/ServerSync#288]
#### Issue: 
![image](https://user-images.githubusercontent.com/10114685/147759155-39196d3e-cc5b-4af0-895d-b1200ab3441b.png)
This is my config
When I set this up and open ServerSync, it just flashes and disappears without any logging.
When I only kept the sync mod function, everything worked fine.
But my server requires players to sync missions.

**Comment by rheimus** [comment]
Presumably you figured this one out.

You probably need to set up config as a managed directory, I would usually use push mode personally as you probably don't want to wipe out user configuration files.

```
"directories": {
  { "path": "config", "mode": "push" }
}
```
