### ISSUE TITLE
Error when using single part locales

### ISSUE THREAD

**Issue by rlane85** [superzanti/ServerSync#289]
Hey, I just discovered this project and decided to give it a shot - I just got the same error on server while running 4.2.0 and was able to workaround it by changing "locale" to "en_US"

> Should be fixed in 4.2.0 https://github.com/superzanti/ServerSync/releases/tag/v4.2.0
> 
> _Originally posted by @rheimus in https://github.com/superzanti/ServerSync/issues/266#issuecomment-877730889_

**Comment by rlane85** [comment]
>

**Comment by rheimus** [comment]
Interesting, the fix for this appears to have gone walking down to the pub.

🤷‍♂️ I'll add it back in again.
