### ISSUE TITLE
ServerSync is not a mod or not working.

### ISSUE THREAD

**Issue by ErythroCraft** [superzanti/ServerSync#294]
#### Issue: 

     Can not load ServerSync as an mod by placing the serversync.jar file in mods folder.
     Server and client has got the same prublem.
     
     Please create a mod to sync serverside and clientside mods.

**Comment by ErythroCraft** [comment]
GameLauncher Crash by installing ServerSync via serversync.exe, too.

**Comment by rheimus** [comment]
Forge changed how mod loading works again, shall have to update it to get the server loading functionality to work with 1.18

**Comment by ErythroCraft** [comment]
jep

I'm closing this because the other issue is the same
