### ISSUE TITLE
Expected ',' or ']' at...

### ISSUE THREAD

**Issue by dd880602** [superzanti/ServerSync#296]
"rules": {
    "directories": [
      {
        "path": "mods",
        "mode": "mirror"
      },
      {
        "path": "resourcepacks",
        "mode": "mirror"
      },
      { "path": "config",
	"mode": "push" 
      }
    ],
    "files": {
      "include": [
        "mods/**"
      ],
      "ignore": [
        "**/serversync-*.jar",
        "**/serversync-*.cfg"
      ],
      "redirect": [
       "pattern": "resourcepacks/**", 
       "redirectTo": "mods"
      ]
    }
*Where does it need to be modified?

**Comment by rheimus** [comment]
Your include list for files is missing a closing bracket.

**Comment by rheimus** [comment]
Your redirect array needs to hold a list of objects.
```
"redirect": [
  { "pattern": "...", "redirectTo": "..." }
]
```
