### ISSUE TITLE
Force replacement mode

### ISSUE THREAD

**Issue by dd880602** [superzanti/ServerSync#297]
How should I force the file to be replaced?
options.txt
optionsof.txt
optionsshaders.txt

**Comment by rheimus** [comment]
Not entirely sure what you are trying to achieve?

Assuming the files exist in a folder called 'stuff' you would add a managed directory for 'stuff' and add a file entry for the files you want to be synchronized.

```
{
  "rules": {
    "directories": [
      {
        "path": "stuff",
        "mode": "mirror"
      }
    ],
    "files": {
      "include": [
        "stuff/options.txt"
      ]
    }
  }
}
```
