### ISSUE TITLE
Running ServerSync on TrueNas

### ISSUE THREAD

**Issue by Luporion** [superzanti/ServerSync#298]
#### Serversync Version: 
newest
#### Minecraft Version: 
any
#### Issue: 
Does anyone have experience on how to configure and run TrueNas with a .jar?
We're trying to create a server which syncs everything to the clients. 
Everything works with classical windows, but i cant wrap my head around on how to properly run the serversync.jar on TrueNas. OpenJDK is already installed.

<details>
<summary>Logs (serverysync & minecraft)</summary>
<pre>

</pre>
</details>

**Comment by rheimus** [comment]
Closing this, it is probably better served as a question in TrueNas community portals.
