### ISSUE TITLE
Wild Card Support

### ISSUE THREAD

**Issue by DPxKnightxZero** [superzanti/ServerSync#3]
Okay I have been thinking to simplify updating a mod it may be useful to add wildcard support so the tool would always sync only the latest wild card deleting the oldest one. An example would be buildcraft.1.2.* may 10th file change time could be replaced by buildcraft 1.2.* may 12 do you realize some mods like the cofh core update hourly? Its a pain to keep files updated with a update stream that large.

**Comment by superzanti** [comment]
I unfortunately will not add support for the server pushing updates to a client. The client has to do it themselves.

The server only serves and does not do things for the client. If the server receives a command it will do what it's instructed. For example one command is 'recursive' the client sends that command and the server responds with all of it's files.

However, I think I can suggest an alternative that will make us both happy.

I can add a function 'updateNeeded' It will ask the server if there has been an update since it last asked. If there has it will go through the update process, if there hasn't it will skip it and connect straight to the server.

How does that sound?

**Comment by DPxKnightxZero** [comment]
I explained this poorly ... what I mean by wildcard the ability for the client to get the latest wildcard * lets say build craft and delete the older version. Otherwise the way server sync works and correct me if I am wrong it can only grab new files it does not remove old or outdated files.

**Comment by superzanti** [comment]
Incorrect. My program updates outdated files.

It compares the checksum between 2 files and if they don't match it updates the file.

**Comment by DPxKnightxZero** [comment]
Do they have to the same file name? How does it detect outdated files?

**Comment by superzanti** [comment]
They have the same file name. It checks to see if the files are different by running a checksum on them.

**Comment by DPxKnightxZero** [comment]
Okay that makes it difficult since most file names change when they update. That would be why wild cards would work better.

**Comment by superzanti** [comment]
It still updates even if the filename changes.

**Comment by DPxKnightxZero** [comment]
Oh okay sounds good then thank you. Also thank you for making the mod work I am not sure what you mean by I didn't update the jar but it might be good to call it 2.1 or 2.2 to show it was changed.

**Comment by superzanti** [comment]
I just updated my github to be 2.2

I also added a feature to make updating faster.

**Comment by DPxKnightxZero** [comment]
Okay I hate to say it but I was right I told it to ignore files and it got them anyways. ... here is the example of a file it keeps downloading after being told to ignore it. 

ignoredfiles {
    # These files are ignored by serversync
    S:IGNORE_LIST <
        ./mods/[Client]-CustomMainMenu-MC1.7.10-1.5.jar
        ./config/CustomMainMenu/mainmenu.json
        ./config/serversync.cfg
        ./config/forge.cfg
        ./config/forgeChunkLoading.cfg
        ./config/splash.properties
        ./mods/[Server]-forgeessentials-1.7.10-1.4.0-beta8-server-731
        ./mods/worldedit-forge-mc1.7.10-6.0.2-SNAPSHOT-dist.jar
        ./mods/[Universal]-serversync-2.0.jar
        ./config/ArchimedesShipsPlus.cfg
        ./config/extrabiomes.cfg

**Comment by DPxKnightxZero** [comment]
I tried a couple of theories and as I suspected it keeps both forge essential versions.
./mods/[Server]-forgeessentials-1.7.10-1.4.0-beta8-server-731
and
./mods/[Server]-forgeessentials-1.7.10-1.4.0-beta8-server-730

It fails to remove old file version.
