### ISSUE TITLE
[Bug] client exe will not starting

### ISSUE THREAD

**Issue by ErythroCraft** [superzanti/ServerSync#303]
#### Serversync Version: 
4.2.0
#### Minecraft Version: 
1.19.2
#### Issue: 
client.exe will not start
<details>
<summary>Logs (serverysync & minecraft)
</summary>
<pre>

The client exe will not start but server side is functionaly perfect.
client side will not download mods from server side.
I don't no why

</pre>
</details>

**Comment by rheimus** [comment]
Most likely that Java FX is missing from your install.

It would be good to remove the dependency on it, for now though it is required unless you use the command line version of the client. e.g. using `progress-only` or `silent` modes

**Comment by ErythroCraft** [comment]
I'll test it. But I wait for the early eccess (March 2032) update.

Maybe you can create an update to test the JavaFX installation by starting the server.

**Comment by rheimus** [comment]
There was an experimental version that packages JFX and the JDK here: https://github.com/rheimus/ServerSync/releases

I don't know how well it works these days, have not tested it in a while. This also means the package size is massively larger as you might expect.
