### ISSUE TITLE
Documentation hasbroken links

### ISSUE THREAD

**Issue by gitgit2019** [superzanti/ServerSync#305]
#### Issue: Documentation is lacking, what are the options for sync_mode and directories mode: mirror? There are also many broken links in the documentation wiki pages.

Can't seem to find this documented anywhere. Wondering if there is an option available to make the directories match exactly by deleting any folders which do not match but also just interested in what settings are available for these options and what they actually do?

**Comment by rheimus** [comment]
The default mode of operation is to make any configured directories match exactly, its the only way to really guarentee that a client can connect.

**Comment by rheimus** [comment]
Do you have more specific pages on the wiki with broken links? They all seem to function properly.
https://github.com/superzanti/ServerSync/wiki/Server-setup
