### ISSUE TITLE
[Server][Feature Request] Create connection whitelist/blacklist ability

### ISSUE THREAD

**Issue by rheimus** [superzanti/ServerSync#45]
Might as well allow the server to refuse connections

**Comment by P3rf3ctXZer0** [comment]
Good plan in case someone attempt too many downloads.

**Comment by teetron9000** [comment]
A suggestion: utilize the **banned-ips.json** and **whitelist.json** of the minecraft server itself, if possible. (Griefers likely to abuse something like this = also likely candidates for bans... If an IP is banned from the server, maybe this should also treat it as banned.)

**Comment by rheimus** [comment]
Tis a good idea, could add a check for the existence of said files and pull in values present

**Comment by rheimus** [comment]
Added support for using minecrafts banned-ips.json. You should be able to either add entries manually to it or use server commands to ban addresses.
e.g. `/ban-ip 127.0.0.1`

**Comment by rheimus** [comment]
Closing in favor of #216
