### ISSUE TITLE
I am a bit lost on instructions can you break it down for stupid people like myself?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [superzanti/ServerSync#46]
""Client:

    Run/Double click serversync{ver}.jar from mods folder (or create shortcut)
""

So I basically copy the Jar twice?

""
Server:

    Pass "server" as an argument to serversync.jar (java -jar serversync{ver}.jar server)

""

So I am not a coder and I am not sure what you mean exactly I am guessing you add it in front of the server startup batch file?

""

(forge*.jar) 
(serversync*.jar)

""

Do you mean forge Version X - X being the version number or filename? Or is it auto detecting?) Same Question with ServerSync Jar?

""

start "Minecraft Server" 
start "ServerSync Server"

""

Do I rename those lines to file versions?

Sorry to ask these questions I just wanted to clarify so maybe in the future I would need to ask others. You seem talented so I wanted to know.

**Comment by rheimus** [comment]
Reopening as a valid issue with the documentation

**Comment by rheimus** [comment]
1. Yep you copy serversync to both the client who wants to synchronize and the server who will be serving the files, serversync sits in the root minecraft directory for both
2. passing arguments on the command line (or in batch files) is done after you call the item in question, in this case we are calling java and passing it serversync as an argument, however we are also passing server as an argument to serversync. Basically all this does is send a string into the main program which we can use to change the behavior slightly (such as running in server mode)
In your batch file this would look like:
- java -jar serversync-2.6.6.jar server
3. The lazy batch file I put in the wiki will grab the first file it finds that matches the pattern (serversync(anything).jar) same for forge, basically this means you don't need to specify an exact version so you don't have to keep updating your start script every time you change forge or serversync
4. start is a program like our java call, start takes a string as its first argument which will become the title of the new window (this argument is required but can also be an empty string if wished) the second argument we are passing to start is the command to run in this new window. %serversync% <- here we are accessing the variable we created earlier by grabbing the first serversync it finds and running it in server mode.
The reason for using start here is that we need to be opening two processes, if we just called them in order:
- java -jar forge
- java -jar serversync
Then the script would block on the first command until completion (usually when forge shuts down) before running serversync, which is not really what we want.

Hopefully that is a bit clearer, It's very easy to phase out step 1 when you do this sort of thing all the time :smile:

I shall scrub the documentation later and make it a bit clearer. Keeping this ticket open until that is completed.

**Comment by rheimus** [comment]
Run/Double click serversync{ver}.jar from mods folder (or create shortcut) -> hah totally conflicting information here. Updated the wiki to remove this as it would be totally confusing, serversync is in the root minecraft directory only for both server and client

**Comment by P3rf3ctXZer0** [comment]
Thank you so much! After some tinkering before you provided the information I managed to figure it out that is why I closed the issue.

**Comment by rheimus** [comment]
Added a section on basic command line use to the wiki
