### ISSUE TITLE
Need a way to pass config folder and subfolders in root folder for mods like pokecube which contain multiple sub folders.

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [superzanti/ServerSync#47]
The serversync application is not actually scanning any configuration files however it is scanning any and all other folders and directories; thank you for this!

**Comment by rheimus** [comment]
Probably broke the config scanning when removing the forge dependency, had to shuffle around things with SyncFiles.

**Comment by rheimus** [comment]
Did some tests, seems like configs are syncing alright.

By default ServerSync will not sync config files unless they are added to the servers include list, I did this as on the whole configs for mods seem to be designed in a non sync friendly way (back when it was just a blacklist of items to not sync you would have to add half your config files in there so that you didn't lose a bunch of user configured items)

**Comment by rheimus** [comment]
Although this does bring up an interesting enhancement, should probably have a file include list that lets you sync from the root directory (it is conceivable that there could be a file users wish to sync that sits in root)

The config sync is a bit janky though as it is just looking for file names, so currently if you specify to sync "myawsomeconfig.cfg" and the config directory is like so:
````
config
    modA
        myawsomeconfig.cfg
    modB
        myawsomeconfig.cfg
````
It will sync both of these files. As raised in #43 I will probably implement some sort of globbing / wildcard support for this.

**Comment by P3rf3ctXZer0** [comment]
So it doesn't actually sync the root of folder configs folder? Yeah that would explain it. Well thank you for explaining that to me.

**Comment by rheimus** [comment]
As for the issue title, should be able to add pokecube's folder to the syncable directories list, its just the config folder that has special handling

**Comment by rheimus** [comment]
Examples are always better so heres one for not syncing all configs by default:

- MyMinimap mod creates a user based config for waypoints, ServerSync synchronizes this confg and wipes out the users waypoints
- Optifine, user based settings for graphics, again wiped by ServerSync
- MyCoolHotkeys, user hotkeys wiped by sync

etc and so on, makes much more of a job for the server admin to keep adding a bunch of config files to the blacklist.

Generally the only time I have needed to sync a config file is for potion ID conflicts, which can be pretty easily added to the config_include_list

**Comment by P3rf3ctXZer0** [comment]
Is there a way to just scan config files? Its just better to keep it scanned and have a blacklist instead, makes less work for server owners ... :( especially ones like me who have 2 kids and a Wife.

**Comment by rheimus** [comment]
Not really sure why mass config sync is needed but hey.

2.6.7 fixes a bug where 0 length files would lock the server and it also removes the enforced config handling.

You can now add config to the directory include list to sync all of them.

**Comment by P3rf3ctXZer0** [comment]
@rheimus thank you very much!
