### ISSUE TITLE
Bug? It tries to synchronize the folder ..\.. 

### ISSUE THREAD

**Issue by XkrulesLP13** [superzanti/ServerSync#49]
As seen above, the mod "ServerSync" tries to synchronize the folder ..\.. (which can only be seen in an FTP-Client (like Filezilla) and is just the way to get one folder up...)
However somehow your mod is not able to differ if the folder is really existing or not.
It could also be that I am just too stupid if this problem is not really one.

http://pastebin.com/fwFWZDjE (especially line 165)
( Failed to create file (..\..): ..\.. (_Zugriff verweigert_) -> permission denied)

Hope that this problem can be fixed soon because otherwise i have to downgrade to an older version of serversync and I really like the Forge decouple version.

**Comment by rheimus** [comment]
Interesting, I'll add some extra sanity checking in there.

It has reached the end of the list with walwa and has somehow picked up an invalid file.

**Comment by rheimus** [comment]
@XkrulesLP13 
The clientfiles list contains ..\.. , was this added to the config by accident or did serversync put it there?

**Comment by rheimus** [comment]
Nvm, relativize is round the wrong way. Shall fix in a mo

**Comment by rheimus** [comment]
Should be fixed in the hotfix version
