### ISSUE TITLE
Wrong folder

### ISSUE THREAD

**Issue by TomberWolf** [superzanti/ServerSync#52]
I've tried this mod today, using the forge version.
The server side works like a charm but on the client side, if I double click the jar, the mod loads all of the server mods into a subfolder "mods".
But that doesn't make any sense if the sync mod itself is in the mods folder.

**Comment by rheimus** [comment]
Forge loaded version is purely for the server side, at the moment client side is always run from minecraft root.
Both versions of SS are compatable with each other.

I'll probably look into dir discovery / CLI args for setting where mc root is.

**Comment by rheimus** [comment]
In the interest of keeping serversync as open as possible I am not going to implement strict directory rules.
