### ISSUE TITLE
Mod rejection when joining server

### ISSUE THREAD

**Issue by syndicate25** [superzanti/ServerSync#54]
I've loaded the Forge version on my server, but when I try to join, I get a mod rejection for not having 2.6.8 in the mods folder on the client side.  I thought that the client side mod had to go in the root directory, which I thought was the .minecraft folder, not the mods folder.  

I guess I could just put a copy of the mod in both the root directory and the mods folder to solve the issue, but I'm trying to eliminate unnecessary mods from loading.

**Comment by rheimus** [comment]
Probably missing a flag to tell forge that its not needed on the client

**Comment by rheimus** [comment]
Added a pre-release of a fix for ServerSync being a client required mod.

The fix as of the moment is untested by me, however it should really work. Potentially might not for 1.7.10 as the cpw version of the Mod annotation did not have any specific definition of which side the mod is intended for. (Presumably this means it also doesn't care which side and will just cause issues if client code is run)

**Comment by rheimus** [comment]
Tested with 1.10.2, sorted
