### ISSUE TITLE
MC-1.10.2 Major Request Serverside 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [superzanti/ServerSync#55]
Need a way to ignore folders and configs.

**Comment by rheimus** [comment]
Probably an issue with legacy naming.

The mod_ignore_list can be used to ignore configs, as of the moment ServerSync makes no real distinction between files when synchronizing.

Probably makes more sense to rename the field to file_ignore_list.

Folder & wildcard support are on my list of improvements as well for the lists

**Comment by P3rf3ctXZer0** [comment]
Sounds fantastic I will happily test anything you release.

**Comment by rheimus** [comment]
Switched the naming of mod_ignore_list to file_ignore_list.

New configs generated by serversync will have this by default, could also change old ones if desired to FILE_IGNORE_LIST, or just let serversync generate a new one and copy the values across.
