### ISSUE TITLE
MC 1.10.2 - Failed to Sync Files?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [superzanti/ServerSync#56]
What does this mean?
https://gist.github.com/P3rf3ctXZer0/c2d75efbc37919137be44c31b218af40

**Comment by P3rf3ctXZer0** [comment]
this is with forge loaded btw.

**Comment by P3rf3ctXZer0** [comment]
It Seems Brandons Core was the cause; please make sure you close this after you read it. Maybe Draconic Evolution requires a fix or maybe Brandon needs to make a fix.

**Comment by rheimus** [comment]
Hmm, doubtful that it's an issue with brandons stuff.

Looks more like I need some extra sanity checks in there, I'm going to add this as a bug to try reproducing as I am cautious of the underlying issue that it may be exposing.

Thank you for the report.

**Comment by rheimus** [comment]
Should also note that the * in your configs ignore list is probably not doing what would be expected.

Will at the moment just be parsing it as a literal char and looking for a file called 'DimensionRules*'.

e.g. if 'MyMod' == 'DimensionRules*' { ignore mod }

**Comment by rheimus** [comment]
Log seems to suggest that the file in question was deleted/moved/altered in some way between the server finding it and the attempted sync process.

This would happen if the file was deleted while serversync was running, can probably be solved with watchers however current serversync does not support changing files while running.

Presumably this did not actually break anything as the contributors list should not be needed for the mod to  function.
