### ISSUE TITLE
Request (Minor) - 1.10.2 Forgeloaded mod and folder reject wilcard support

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [superzanti/ServerSync#57]
Example "mod*.jar" maybe even "mod*"

**Comment by rheimus** [comment]
not sure about adding mod detection. There's not a lot to tie into for detecting what qualifies as a mod, it also tightly couples serversync to minecraft specifically.

Technically serversync alredy scans the mcmod.info of mods so I could tie into that, but it's really not a stable way of detecting mods.

Wildcard support is a part of the 2.7 project, probably coming in after connection white/blacklisting

**Comment by VOiDProXy** [comment]
Looking forward to wildcard support :)
Going through line by line to ignore version numbers off by a digit is tedious, but still better than dealing with all my clients going "HELP WHAT DO I DO NOW, WHAT FOLDER?"

**Comment by rheimus** [comment]
Yeah, I was never terribly happy with the way I've implemented the ignore/include lists.

I might actually bump the wildcarding up in priority, shouldn't be terribly difficult to get a basic system working either.

**Comment by rheimus** [comment]
Added glob support in 2.6.11
