### ISSUE TITLE
Extreme Console Spam Cannot Upload to Gist Please help @.@

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [superzanti/ServerSync#59]
https://www.dropbox.com/s/gj274uvlfk9cu1h/fml-server-latest.log?dl=0

**Comment by P3rf3ctXZer0** [comment]
Okay so same issues that you thought caused sanity check fails may also be causing this (I have no idea what a sanity check is.) At any rate when this happens the server hangs and must be killed not closed.

**Comment by rheimus** [comment]
Sanity checks are pieces of logic that should never need to be executed, things like:
- load a file
- check if file is a file (shouldn't happen as you just loaded a file)

**Comment by rheimus** [comment]
Interesting the log highlights a totally separate problem, language checks are not handling lowercase versions of the codes (en_us != en_US)

**Comment by rheimus** [comment]
[STDOUT/com.superzanti.serversync]: [com.superzanti.serversync.ServerSetup:run:140]: socket alredy bound at: 38067

Potentially relevant line (Ignore my rambling if you like, am using it to keep track of information mostly)

**Comment by rheimus** [comment]
Seems to be hitting a null pointer inside a loop, creates an endless lock of attempting to access a non-existent resource

**Comment by rheimus** [comment]
```java
while (true) {
	try {
		Socket socket = server.accept();
		ServerWorker sc = new ServerWorker(socket, server, generateServerMessages());;
		Thread clientThread = new Thread(sc);
		clientThread.setName("ClientThread - " + socket.getInetAddress());
		clientThread.start();
	} catch (Exception e) {
		e.printStackTrace();
	}
}
```
Presumably server is null here for some reason, probably related to the socket binding.

**Comment by P3rf3ctXZer0** [comment]
Always glad to help ;)

**Comment by rheimus** [comment]
The problem here will gracefully fail in 2.6.10.

However there is a separate problem in that your port: 38067 was already bound to something else.
