### ISSUE TITLE
Forge Loaded Version forces itself client side to join server

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [superzanti/ServerSync#60]
So while testing I found that if the forgeloaded version must be client side for clients to connect ... any thoughts?

**Comment by rheimus** [comment]
#54 has an untested fix for the client requirements in the releases.

**Comment by P3rf3ctXZer0** [comment]
Where can I find this fix?

**Comment by rheimus** [comment]
https://github.com/superzanti/ServerSync/releases

**Comment by rheimus** [comment]
The new release 2.6.9 sorts the client required problem

**Comment by P3rf3ctXZer0** [comment]
is this a forgeloaded hybrid?

**Comment by rheimus** [comment]
Yes, forge loaded and normal were identical so I merged them. Shall update the wiki 😀
