### ISSUE TITLE
Issue - Failing to Include Configs

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [superzanti/ServerSync#64]
rules {
    S:CONFIG_INCLUDE_LIST <
    CustomMainMenu
    >

It just ignores it completely.

**Comment by rheimus** [comment]
probably needs the specific file at the moment,

```
rules {
    S:CONFIG_INCLUDE_LIST <
        menu.json
    >
}
```

**Comment by rheimus** [comment]
With 2.6.11 you should be able to specify CustomMainMenu/*
