### ISSUE TITLE
Request: Run ServerSync when Joining Server

### ISSUE THREAD

**Issue by Paradigm999** [superzanti/ServerSync#67]
Before I start, I just want to say that I have no idea how Minecraft works and that I have not done any programming in a few years, and never in Java.

That said, Would it be possible to have ServerSync run when the MC server is joined?
This would allow people to join any server with any mod combination and it would just work.
It would be the "Holy Grail" of mod syncing for MC servers.

ServerSync's configuration could also be handled through the MC GUI at the main menu by clicking on the Mods button and then selecting Config for the ServerSync mod.
Each server would require its own entry in the config file in order to work properly.
OR... 
Could the server be contacted for port information for syncing?

From my meager experiences in programming I do know that this is no small task but it would be really helpful for novices. It would allow people who don't know anything about computers to easily join modded servers.

**Comment by rheimus** [comment]
This was the original ideal behind ServerSync, and I would love to do exactly that.

The catch:
Forge / Minecraft takes a loooong time to load mods, the only way to connect to a server using native Minecraft is to have the game loaded (i.e. ModLoader has completed all of its loading lifecycle).

At this point we have several problems:
- Forge is holding references to mods in memory (cant safely modify / delete files)
- If files are modified then forge needs to restart / reload its mod environment (long load time)
- Forge can not provide a reliable way of having ServerSync run first (not that I know of anyway, and it wouldn't work for this case anyway as it's when joining a server)

This kind of functionality would probably require writing a custom launcher / server browser that has knowledge of which servers are running ServerSync which at the moment is a bit beyond my time capabilities. (or rewrite ModLoader to use a more lazy load approach, mods loaded after joining server)

The best I can do for now, which is on the cards is have Client ServerSync start Minecraft after it's done, or something like #65.

**Comment by rheimus** [comment]
It is potentially possible to have Forge unload / reload specific mods, however I have not looked into the deeper problems that could arise from this (dependencies comes to mind)

**Comment by Paradigm999** [comment]
Thank you for the explanation. 
It would be annoying to have to wait for Forge to load twice and, as you said, unloading mods would probably cause a crash.

I'm going to look into running the MC with command line arguments to try a direct server connection.

**Comment by P3rf3ctXZer0** [comment]
Any update on this?

**Comment by rheimus** [comment]
Not from my end, have been focusing mostly on getting current functionality working well and fixing bugs.

You can run the launcher and possibly even connect to a server via command line, briefly read some info about it on a wiki. It would need to be a per client manual thing though as you would need the username and password as well

**Comment by hugeblank** [comment]
What I would recommend honestly is taking a step back, and rather than making it run on server join, have it start on client startup. You could make a custom launcher and everything, so that when it syncs, it automatically launches minecraft. _THAT_ is both feasible, and "easy"* to do, considering you already have a decent enough UI.
*easy in comparison to Paradigm's post. 

Here's a couple of things you probably would have to do though:
- Have the user pick from a _forge_ version of minecraft (in .minecraft/versions)
- add a config option to autosync when "launch" is pressed. (Considering that server creators [like myself] would probably provide a version of the mod that has the server IP and port provided in config already.)

**Comment by P3rf3ctXZer0** [comment]
@hugeblank I am sorry I have to disagree because I would be forced to change my prefered launcher again now if he integrated into Multi-MC I think it would be great because code is open source and they be will to add support directly for server-sync! Not to mention he is another Dev I have helped beta a bunch so I know he means business.

**Comment by rheimus** [comment]
Rolling into an already established launcher would probably be better in the end than anything I could produce on my budget of time.

**Comment by rheimus** [comment]
Blocked:
Waiting on forge to support what we are trying to achieve. We really need some form of hot reloading for mods.

**Comment by P3rf3ctXZer0** [comment]
@rheimus have you been able to contact @LexManos he is the the feature guy I thought.

**Comment by rheimus** [comment]
@P3rf3ctXZer0 
I have not no, I have mostly been slowly digesting enough of Forge to actually have any form of meaningful conversation around it.

At the moment I don't know enough about how the mod loading works.

**Comment by Paradigm999** [comment]
I actually did switch over to using MultiMC with a pre-launch command and it works great.

**Comment by P3rf3ctXZer0** [comment]
how?

**Comment by Paradigm999** [comment]
If you edit an instance in MultiMC, go to Settings, then click on the "Custom commands" tab you can add a pre-launch command. Here is the command that I use:
java -jar serversync-2.6.13.jar progress-only

**Comment by rheimus** [comment]
can also use the silent option if you don't want any UI present.

**Comment by P3rf3ctXZer0** [comment]
Yeah this issue should be closed @rheimus
