### ISSUE TITLE
Unable to download mods while using technic

### ISSUE THREAD

**Issue by DPxKnightxZero** [superzanti/ServerSync#7]
After testing the mod in a technic test modpack the mod does not understand how to parse the modpack directory so it downloads the mods and deletes them right away. Effectively defeating the purpose I wanted to use it for.

**Comment by superzanti** [comment]
Try it with the latest version.

**Comment by DPxKnightxZero** [comment]
https://drive.google.com/file/d/0B1fY2sKXiHd7QzJPOVlZNkdqOU0/view?usp=sharing
Still an issue. ... See you later night :P

**Comment by DPxKnightxZero** [comment]
okay fixed a single mod issue. 

Anyways the other mods remained an issue.
![2015-06-08_04 58 01](https://cloud.githubusercontent.com/assets/10351221/8032361/1984bba8-0d9b-11e5-990f-721b1859e962.png)

**Comment by superzanti** [comment]
Send me your client again so I can look it over

**Comment by DPxKnightxZero** [comment]
I am not sure what your asking ... but I will send you my technic modpack download string. You will need the technic plateform to make any use of it. http://www.technicpack.net/download and here is my modpack:  http://www.technicpack.net/modpack/zer0verse.670441 How to install  a modpack : https://technicpack.zendesk.com/hc/en-us/articles/204020115-How-to-Install-Modpacks

**Comment by superzanti** [comment]
Can you just install it then zip-up your .minecraft folder and then send that to me via mega.co.nz?

**Comment by DPxKnightxZero** [comment]
no because in order to recreate the issue you have to do exactly what I have done.

**Comment by DPxKnightxZero** [comment]
Its not an issue with .minecraft its an issue directly with the file tree technic uses.

**Comment by superzanti** [comment]
My mod does not deal with anything outside of the .minecraft folder.

It must be an issue with whatever technic is doing.

**Comment by DPxKnightxZero** [comment]
technic does not use .minecraft ... I am saying you need to add support.

**Comment by DPxKnightxZero** [comment]
Here is an example file tree that technic modpacks uses C:\Users\P3rf3ct_Zer0\AppData\Roaming\.technic\modpacks\zer0verse\mods

**Comment by superzanti** [comment]
We're getting into very specific applications here. This may not be something  can fix easily without losing support for other things.

I will look into it tonight though.

**Comment by DPxKnightxZero** [comment]
I understand please take your time. I would rather it work then be problematic. So for the time being I release a repacked client as I did for you specifically mimicing the minecraft folder tree. Even though it looks shady for the time being I have no choice.

**Comment by DPxKnightxZero** [comment]
https://github.com/superzanti/ServerSync/issues/9
