### ISSUE TITLE
Console lag

### ISSUE THREAD

**Issue by rheimus** [superzanti/ServerSync#70]
#### Issue: 
Seems that after a while the console starts having major input lag, investigate if this is serversync causing it

<details><summary>Logs (serverysync & minecraft)</summary><p>

</p></details>

**Comment by MarS301** [comment]
I can confirm this problem. Adding serversync to forge mod-folder results in input lag (Windows command prompt as well as Mac Terminal). If I remove the jar everything is back to normal.

Serversync Version: 2.6.12
Minecraft Version: 1.10.2
Forge: 12.18.3.2185

**Comment by rheimus** [comment]
SS appears to be rock solid in terms of memory use while idle.

**Comment by rheimus** [comment]
Ran SS for several hours on a test server with a fresh build. Saw no console lag.

Shall test on the server I confirmed the console lag on to see if i just failed to build the right version.

**Comment by rheimus** [comment]
Could not reproduce console lag in various environments
