### ISSUE TITLE
Server Side Only mods

### ISSUE THREAD

**Issue by Endmateria** [superzanti/ServerSync#78]
#### Issue: I have some mods that are server side only i.e., I don't want them to transfer over to the client.  I've put the names of the specific mods in the file ignore lists (both server and client config files), but the files still transfer to the client regardless.  Am I going about this the wrong way?  Serversync seems to be ignoring the file ignore lists.

Here's my current server and client configs for reference... https://gist.github.com/Endmateria/f29adc3c686706736e8d8d604e81a3a3#file-serversync-client-cfg

**Comment by rheimus** [comment]
Apologies for the late reply, somehow missed the notification for this one.

The file ignore list is evaluated from the Minecraft folder. So those entries just need mods/ in front of them.

**Comment by Endmateria** [comment]
Makes sense, thanks!
