### ISSUE TITLE
Immediate failure to connect

### ISSUE THREAD

**Issue by TheQuantumGeneral** [superzanti/ServerSync#8]
I set up a test server to try this out, got the Minecraft port and the server sync working port both port fowarded, button was set up with your config examples. Screen immediately goes to "Closing connections 99%" and freezes.

Do I need to set some additional firewall exceptions or something? It is late here so apologies if this is an obvious user error issue. 

![capture](https://cloud.githubusercontent.com/assets/7843312/8038440/ea6288b2-0e46-11e5-8709-96dcb6f11402.PNG)

**Comment by superzanti** [comment]
So the error you're getting is "Connection refused: connect"

Assuming the ip address is right and the port is correct, it is likely that you need to add an exception for the port in your firewall.

Somewhere between your client and the server something is blocking the connection.

Here are some suggestions
* Is both the server and the client on the same network?
  * If so you probably need to use the internal ip and not the external one.
  * If not, make sure you're using the external ip and both the client and server are on the same port
* Try disabling all anti-virus and firewalls to see if it works. If it does we'll have to figure out how to add the appropriate exceptions

Can you put your entire log in pastebin and repost?


In terms of my code, I still have a bug where it doesn't timeout. I know exactly which line it's breaking on:
```
socket.close()
```
And for some reason if the socket never connected, then it won't timeout when it tries to close this socket that was never opened.

**Comment by TheQuantumGeneral** [comment]
Server is on the network on a different port 

Using the internal or the external IP now give me the same thing, it says "Finished, working 100%" and times out a few seconds later.

![captur2e](https://cloud.githubusercontent.com/assets/7843312/8049816/9d4e50ea-0ea7-11e5-8a86-76c226f8e3eb.PNG)
![capture](https://cloud.githubusercontent.com/assets/7843312/8049819/a03e9152-0ea7-11e5-94d9-18967ee667e9.PNG)

Here's the full client log when this happens - http://pastebin.com/gdbzywga Ip addresses omitted 

Full server log when this happens - http://pastebin.com/13ZTuR0v

**Comment by superzanti** [comment]
^-- Everyone let that be an example on how to ask for help.

But one more thing, Can I see your serversync.cfg?

**Comment by TheQuantumGeneral** [comment]
Serversync.cfg

http://pastebin.com/pJS7m6jx

**Comment by superzanti** [comment]
The first thing I notice is that you're using the newest version. So that's good :)

Second thing I noticed you blanked out your ip. If you are on the same network as your computer make sure it's the internal IP address. not your  external ip.

Are you using something other than vanilla? Could this be related to issue #7 ?

Can you connect to your server by only removing my mod? Because based on the logs, it seems my mod is working very well.

**Comment by TheQuantumGeneral** [comment]
Ive tried the internal IPv4 address, external IP and the external hostname that I use, all giving the same error I posted above. 

It is a modded server, myself and the others who play on it have no connectivity issues normally.  
I don't think its related to Issue #7, the pack is normally a private pack on the Technic launcher but these tests were done through MultiMC launcher using the latest Forge, I did try your recommended Forge build 1403 but the result was the same. 

I'll play around with it some more, i'll post back here if I have any success.

**Comment by TheQuantumGeneral** [comment]
Okay, user error, i'm an idiot. When I made a new directory to test this out safely I didn't copy the server.properties file, so I expected it to be running on 25566 like the server normally would, but it defaulted back to 25565 when it generated the new file. 

fixed the port settings and it now works. Thanks for the help, apologies for the goose chase.

**Comment by superzanti** [comment]
That's really good to hear! Thank you very much for letting me know.
Feel free to suggest features or report bugs.
