### ISSUE TITLE
ServerSync takes long time after finishing

### ISSUE THREAD

**Issue by TomberWolf** [superzanti/ServerSync#80]
#### Serversync Version: 
serversync-2.6.15

#### Minecraft Version: 
1.10.2

#### Issue: 
ServerSync takes a long time after checking updates til it closes (nearly 2 minutes).
No matter if there are updates available or not.

So if you run it in a batch file before the MC launcher starts, it's just wasted time.

**Comment by cragrim** [comment]
When running the "deleting mods" process it seems to halt for a bit doing nothing, even when there are no mods to delete. For me its it's about 5-10 seconds. No biggie though.

**Comment by rheimus** [comment]
Hmm, I have noticed that SS pauses for a moment there. Shall have to dig into some profiling tools.

The most expensive operation should be the scan for mods, which in most of my testing is < 1 second.

**Comment by TomberWolf** [comment]
Nevermind, I'm just an idiot!!
I've updated the client version but not serversided. It works like a charme!
