### ISSUE TITLE
No sync for config file

### ISSUE THREAD

**Issue by TomberWolf** [superzanti/ServerSync#83]
#### Serversync Version: 
serversync-2.6.15

#### Minecraft Version: 
1.10.2

#### Issue: 

I have a config file included in the serversync-server.cfg but it won't be copied to the client's config folder.

```
rules {
    S:CONFIG_INCLUDE_LIST <
        debugserverinfo.cfg
    >
```

**Comment by rheimus** [comment]
Hmm is possible that I've broken this in the globbing support change. Shall investigate

**Comment by rheimus** [comment]
Confirmed that config files are not following include rules properly.

Shall prioritize this as it's a fairly glaring failure of functionality.

**Comment by rheimus** [comment]
This was an oversight, technically it worked the include list just needed "config/" added in front of each entry.

Being rather redundant at the moment though I just changed the include matcher to do this for us.
