### ISSUE TITLE
Request - ServerSync 1.12.1 Please and Thank you

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [superzanti/ServerSync#84]
Wondering if you could make a version for latest forge happy to beta as always XD

**Comment by rheimus** [comment]
Downloaded the latest 1.12.1 server and tested with current SS.

Seems to work as expected, was there something in particular that was not working?

**Comment by P3rf3ctXZer0** [comment]
Oh my bad I will set it up then XD
