### ISSUE TITLE
Information - Updated Tutorials on MultiMc use of Server Sync

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [superzanti/ServerSync#85]
I don't know if you want these but they partially apply to a usage of server sync in a practical fashion.

If nothing else I gave you props!

Part 1
https://www.youtube.com/watch?v=k9_TANtuNE8&t=8s

Part 2 
https://www.youtube.com/watch?v=bpXW4HSbZyg

**Comment by rheimus** [comment]
Nicely done, those are some well presented tutorials.

Minor note:
superzanti is the original author of ServerSync, I took over maintaining the project.

**Comment by P3rf3ctXZer0** [comment]
@rheimus :X I will make sure to change that in future credits ... I am so sorry I haven't given you credit </3

**Comment by rheimus** [comment]
All good by me, 😀
