### ISSUE TITLE
Feature request [1.7.10]

### ISSUE THREAD

**Issue by syndicate25** [superzanti/ServerSync#87]
#### Serversync Version: 
2.6.9
#### Minecraft Version: 
1.7.10
#### Issue: 
Would it be possible to add a config *exclusion* instead of a config *inclusion* list?  I have 164 mods, and some of which have folders with multiple configs to list and include.  It's quite tedious to update a list that large.. whereas, I could simply tell serversync NOT to send xyz configs to the client, and it can have the rest.  That would be a most useful feature.

**Comment by rheimus** [comment]
It's a very hidden feature but you can achieve this by adding config to the file_include_list.

This will sync everything in the config directory, then you can use the file_ignore_list as usual to ignore a specific config.

Make sure the config include list is empty when doing this as I believe it overrides.

I really do need to streamline the inclusion/exclusion system though.

**Comment by rheimus** [comment]
Versions 2.6.12 onwards also have globbing support for the exclusion lists

**Comment by rheimus** [comment]
Closing this in favor of a cleanup task later down the line. Shall add some docs to the wiki
