### ISSUE TITLE
Ignore and Include lists

### ISSUE THREAD

**Issue by frakier** [superzanti/ServerSync#88]
#### Serversync Version: 
2.6.16.aplha.2
#### Minecraft Version: 
1.10.2 forge 1.10.2-12.18.3.2281
#### Issue: 
Needed to protect a folder in the mods folder on the client side.
The folder is used by VoxelMods to store map data

<details>
<pre>
-Tried in the FILE_IGNORE_LIST
	mods/VoxelMods/*
	-the files in the immediate folder are protected as well as the sub-folder structure.
	However all other files are deleted.
-So I tried again with this in the FILE_IGNORE_LIST..
		mods/VoxelMods/* {immediate files protected sub-folders protected}
		mods/VoxelMods/voxelMap/* {immediate files protected sub-folders protected}
		mods/VoxelMods/cache/* {sub-folders protected}
		mods/VoxelMods/cache/metalski.game-host.org~colon~25566/* {sub-folders protected}
		mods/VoxelMods/cache/metalski.game-host.org~colon~25566/Overworld (dimension 0)/* {immediate files protected sub-folders protected}
		mods/VoxelMods/cache/metalski.game-host.org~colon~25566/Nether (dimension -1)/* {immediate files protected sub-folders protected}
		mods/VoxelMods/cache/metalski.game-host.org~colon~25566/Deep Dark (dimension -11325)/* {immediate files protected sub-folders protected}
		mods/VoxelMods/cache/metalski.game-host.org~colon~25566/Cavern (dimension -50)/* {immediate files protected sub-folders protected}
		mods/VoxelMods/cache/metalski.game-host.org~colon~25566/Caveland (dimension -53)/* {immediate files protected sub-folders protected}

-Suspect the reason for the problem is the space in the "Overworld (dimension 0)" folder names.
</pre>
</details>

**Comment by rheimus** [comment]
@frakier 
You are probably looking for mods/VoxelMods/**/*

That glob pattern will match anything in the directory mods/VoxelMods/(any sub directory)/(any file)

**Comment by frakier** [comment]
Worked, my misunderstanding on how the blob worked.
