### ISSUE TITLE
clientmods folder and non jar file

### ISSUE THREAD

**Issue by frakier** [superzanti/ServerSync#89]
#### Serversync Version: 
2.6.16.aplha.2
#### Minecraft Version: 
1.10.2 forge 1.10.2-12.18.3.2281
#### Issue: 

Added a liteloader mod to the clientmods folder and it was ignored
<details>
<pre>
(First try)
	added the liteloader mod mod_voxelMap_1.6.23_for_1.10.2.litemod 
	-the file was ignored and the file was deleted on the client
(Second Try)
	-I was able to add the file to the ignore list mods/mod_voxelMap*.litemod and the file was ignored
 not the best option but it worked.

-Suspect the file extension not being jar could be the problem
</pre>
</details>

**Comment by rheimus** [comment]
Interesting, reasonably sure that SS is not checking what file type is being used.

It does attempt to get mcmod.info from standard mods but if it fails it should just consider the file 'misc' and use hash comparison.

**Comment by rheimus** [comment]
Created a bogus file with the litemod extension in a test clientmods.

Seems to sync fine and pick it up on later sync attempts as well, mods in the clientmods folder should not need to be added to any of the exclusion lists.

Could you post the server/client config in use.

**Comment by frakier** [comment]
Worked....

Client only mod added: mod_voxelMap_1.6.23_for_1.10.2.litemod
mod_voxelMap_1.6.23_for_1.10.2.litemod is up to date

I'm going to use the excuse I was up really late the night before and just misssed this [multiple times] but it is working now so I'm good. Hey maybe I forgot to put the mod in the clientmods folder.
