### ISSUE TITLE
Serversync doesn't ignore certain subfolders in config

### ISSUE THREAD

**Issue by vpontin** [superzanti/ServerSync#90]
#### Issue: 

Hi! I have two subfolders in my clients `config` folder (related to Xaero's World Map - a clientmod): `XaeroWaypoints` and `XaeroWorldMap`, and no matter how i put its paths (relative or only its folder names) i cant make serversync ignore them and not remove them and its files from my client installations during syncs.

Is this intended?

Can you add the possibility to ignore certain folders (and files) from config?

Thanks!

**Comment by rheimus** [comment]
config/*Xaero*/**/*

Should give you the desired effect, will ignore all files and subfolders inside the config directory that reside in a folder that contains the string xaero

**Comment by vpontin** [comment]
Thanks, closing it for now.
If something odd happened, i will report back.
