### ISSUE TITLE
Ignoring Ignore Lists ServerSync 1.12.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [superzanti/ServerSync#96]
#### Serversync Version: 
serversync-2.6.16-alpha.2.jar
#### Minecraft Version: 
1.12.2 - 14.23.1.2589
#### Issue: 
Ignoring Ignore Lists

[serversync.zip](https://github.com/superzanti/ServerSync/files/1633195/serversync.zip)

**Comment by P3rf3ctXZer0** [comment]
Keeps deleting the files on client side. No matter what I do.

**Comment by rheimus** [comment]
Interesting, I would not expect a minecraft update to influence SS.

Shall load up a 12.2 test and see what I can find.

**Comment by rheimus** [comment]
@P3rf3ctXZer0 
Seems like your config is looking for a file in the base directory of minecraft.

As SS can sync files in folders other than mods it requires the list to declare which folder it is looking for.

e.g. mods/foo.jar.

My super basic test setup appears to ignore files as expected, although it does sync serversync itself which it should not be doing.

**Comment by rheimus** [comment]
Closing in favor of #97
