### ISSUE TITLE
[Client] Investigate performance on lower end machines

### ISSUE THREAD

**Issue by rheimus** [superzanti/ServerSync#98]
#### Issue: 
#86 

> It seems to happen with certain pcs and a large number of updates. Suddenly my users are experiencing issues. We have been using server-sync for months. At any rate I have not had issues personally. Also all the reports come from computers with 8GB rams or less. Also fun fact weaker hard-drives seem to be a factor as well.

Investigation needed on the performance cost of SS on lower end machines, potential for memory hogging with large numbers of files.

**Comment by Hexawolf** [comment]
Turning all files into a single huge serialized list and transferring it over network is a totally wrong way of doing thing. I think entire file transfer code must be written from scratch.

**Comment by rheimus** [comment]
Did you have a proposal in mind.

**Comment by Hexawolf** [comment]
Obviously, saving them separately is a way it must work. Looking at code, right now you just serialize entire list and send it as a single entity via network.
